{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Interface plate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from build123d import *\n",
    "import scrollcase as sc\n",
    "import logging\n",
    "from functools import partial\n",
    "from ocp_vscode import *\n",
    "from dataclasses import dataclass\n",
    "\n",
    "logging.basicConfig()  # Required in Jupyter to correctly set output stream\n",
    "logging.getLogger(\"scrollcase\").setLevel(logging.DEBUG)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "@dataclass\n",
    "class interface_specs:\n",
    "    plate_width_mm: float = 140\n",
    "    plate_depth_mm: float = 10\n",
    "\n",
    "    box_width_mm: float = 12.5\n",
    "    box_height_mm: float = 6.5\n",
    "\n",
    "    captive_nut_holder_outer_diam_mm: float = 135\n",
    "    captive_nut_holder_inner_diam_mm: float = 115\n",
    "    captive_nut_holder_height_mm: float = 10\n",
    "    captive_nut_holder_width_mm: float = 50\n",
    "\n",
    "    captive_nut_slot_width_mm: float = 13\n",
    "    captive_nut_slot_depth_mm: float = 6.25\n",
    "    captive_nut_slot_distance_apart_mm: float = 117.5\n",
    "\n",
    "    bolt_hole_diameter_mm: float = 6.8\n",
    "\n",
    "\n",
    "specs = interface_specs()\n",
    "\n",
    "def interface_plate():\n",
    "    with BuildPart() as part:\n",
    "        # Base plate\n",
    "        Box(\n",
    "            specs.plate_width_mm,\n",
    "            specs.plate_width_mm,\n",
    "            specs.plate_depth_mm,\n",
    "            align=(Align.CENTER, Align.CENTER, Align.MAX),\n",
    "        )\n",
    "\n",
    "        # Cylinder on top of the plate\n",
    "        Cylinder(\n",
    "            radius=specs.captive_nut_holder_outer_diam_mm / 2,\n",
    "            height=specs.captive_nut_holder_height_mm,\n",
    "            align=(Align.CENTER, Align.CENTER, Align.MIN),\n",
    "        )\n",
    "\n",
    "        # Subtract inner cylinder\n",
    "        Cylinder(\n",
    "            radius=specs.captive_nut_holder_inner_diam_mm / 2,\n",
    "            height=specs.captive_nut_holder_height_mm,\n",
    "            align=(Align.CENTER, Align.CENTER, Align.MIN),\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "\n",
    "        # Captive nut holders\n",
    "        with Locations((specs.captive_nut_holder_width_mm / 2, 0, 0)):\n",
    "            Box(\n",
    "                specs.plate_width_mm,\n",
    "                specs.plate_width_mm,\n",
    "                specs.captive_nut_holder_height_mm,\n",
    "                align=(Align.MIN, Align.CENTER, Align.MIN),\n",
    "                mode=Mode.SUBTRACT,\n",
    "            )\n",
    "\n",
    "        with Locations((-specs.captive_nut_holder_width_mm / 2, 0, 0)):\n",
    "            Box(\n",
    "                specs.plate_width_mm,\n",
    "                specs.plate_width_mm,\n",
    "                specs.captive_nut_holder_height_mm,\n",
    "                align=(Align.MAX, Align.CENTER, Align.MIN),\n",
    "                mode=Mode.SUBTRACT,\n",
    "            )\n",
    "\n",
    "        # Captive nut slots\n",
    "        with Locations((0, specs.captive_nut_slot_distance_apart_mm / 2, 0)):\n",
    "            Box(\n",
    "                specs.captive_nut_slot_width_mm,\n",
    "                specs.captive_nut_slot_depth_mm,\n",
    "                specs.captive_nut_holder_height_mm,\n",
    "                align=(Align.CENTER, Align.MIN, Align.MIN),\n",
    "                mode=Mode.SUBTRACT,\n",
    "            )\n",
    "\n",
    "        with Locations((0, -specs.captive_nut_slot_distance_apart_mm / 2, 0)):\n",
    "            Box(\n",
    "                specs.captive_nut_slot_width_mm,\n",
    "                specs.captive_nut_slot_depth_mm,\n",
    "                specs.captive_nut_holder_height_mm,\n",
    "                align=(Align.CENTER, Align.MAX, Align.MIN),\n",
    "                mode=Mode.SUBTRACT,\n",
    "            )\n",
    "\n",
    "        # Bolt holes\n",
    "        with Locations((0, 0, specs.captive_nut_holder_height_mm / 2)):\n",
    "            Cylinder(\n",
    "                radius=specs.bolt_hole_diameter_mm / 2,\n",
    "                height=specs.plate_width_mm,\n",
    "                align=(Align.CENTER, Align.CENTER, Align.CENTER),\n",
    "                rotation=(90, 0, 0),\n",
    "                mode=Mode.SUBTRACT,\n",
    "            )\n",
    "\n",
    "        # Alignment box\n",
    "        Box(\n",
    "            specs.box_width_mm,\n",
    "            specs.box_width_mm,\n",
    "            specs.box_height_mm,\n",
    "            align=(Align.CENTER, Align.CENTER, Align.MIN),\n",
    "        )\n",
    "\n",
    "    return part\n",
    "\n",
    "plate = interface_plate()\n",
    "show(plate, reset_camera=Camera.KEEP)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
