import React from "react";
import Link from "@docusaurus/Link";
// The dimensions manifest is generated by scripts/genImageDimensions.js before
// every `yarn start` / `yarn build`. The rehype plugin that normally stamps
// width/height only sees raw <img> in markdown — never images rendered by a
// component — so Figure stamps them itself to keep layout shift at zero.
import DIMS from "@site/.image-dimensions.json";

// Content figure, styled by the .vc-fig family in src/css/chrome.css.
//
//   <Figure variant="pair" srcs={[a, b]} alts={["…", "…"]}
//           subCaptions={["DLS, 7.91 µm", "ESRF, 2.4 µm"]}
//           caption="Shared caption with a [link](/data)." />
//
// variant: "full" | "medium" | "pair" | "stack" (required)
// card:    surface plate behind the media (for white diagrams / multi-panels)
// enlarge: wrap image(s) in <a href={file}> opening the raw file in a new tab
//          (bypasses the lightbox — the delegated zoom handler skips images
//          inside links). Non-enlarged images keep the `zoomable` lightbox.
// maxWidth:  px cap on the figure (medium defaults to 560 via CSS)
// maxHeight: px cap per image; portraits are auto-capped at 640 when the
//            manifest knows their dimensions (80vh on phones, via CSS)

// Caption strings may carry [text](/path) links (contract with WP-B). Parsed
// into React elements — same safety rules as ChatWidget/MarkdownLite: internal
// paths client-side navigate, http(s) opens a new tab, anything else (unknown
// schemes, javascript: …) renders as plain text. Links only, no other markdown.
function renderCaption(text, keyPrefix) {
  if (typeof text !== "string") return text; // JSX captions pass through
  const link = /\[([^\]]+)\]\(([^)\s]+)\)/g;
  const nodes = [];
  let last = 0;
  let k = 0;
  let match;
  while ((match = link.exec(text)) !== null) {
    if (match.index > last) nodes.push(text.slice(last, match.index));
    const key = `${keyPrefix}.${k}`;
    const label = match[1];
    const url = match[2];
    if (url.startsWith("/") || url.startsWith("#")) {
      nodes.push(
        <Link key={key} to={url}>
          {label}
        </Link>
      );
    } else if (/^https?:\/\//i.test(url)) {
      nodes.push(
        <a key={key} href={url} target="_blank" rel="noopener noreferrer">
          {label}
        </a>
      );
    } else {
      nodes.push(label);
    }
    last = link.lastIndex;
    k += 1;
  }
  if (last < text.length) nodes.push(text.slice(last));
  return nodes;
}

function FigImage({ src, alt, enlarge, maxHeight }) {
  const dims = DIMS[src] || null;
  // Portraits get a height cap so they don't tower over the prose; an explicit
  // maxHeight prop wins.
  const cap =
    maxHeight != null ? maxHeight : dims && dims[1] > dims[0] ? 640 : null;
  const className = [!enlarge && "zoomable", cap && "vc-fig__img--capped"]
    .filter(Boolean)
    .join(" ");
  // Express the height cap as an explicit *display width* (the width at which
  // the image's height equals the cap). A definite width — not width:auto — is
  // what lets the browser reserve the correct height BEFORE a loading="lazy"
  // image decodes: width:auto collapses an unloaded lazy image to ~2px, so the
  // real height only appeared on load, shoving everything below down by
  // ~400px and leaving #anchor links parked above their target. CSS caps it
  // with max-width:100% so it still shrinks in narrow columns / on phones,
  // height:auto keeping the ratio (and staying under the cap). This is the same
  // reservation mechanism the uncapped images already use.
  const capWidth = cap && dims ? Math.round((dims[0] * cap) / dims[1]) : null;
  const img = (
    <img
      src={src}
      alt={alt || ""}
      width={dims ? dims[0] : undefined}
      height={dims ? dims[1] : undefined}
      loading="lazy"
      decoding="async"
      className={className || undefined}
      style={capWidth ? { width: `${capWidth}px` } : undefined}
    />
  );
  if (!enlarge) return img;
  return (
    <a
      className="vc-fig__enlarge"
      href={src}
      target="_blank"
      rel="noopener noreferrer"
    >
      {img}
    </a>
  );
}

export default function Figure({
  variant,
  card = false,
  src,
  alt,
  srcs,
  alts,
  subCaptions,
  caption,
  enlarge = false,
  maxWidth,
  maxHeight,
}) {
  const sources = Array.isArray(srcs) ? srcs : src ? [src] : [];
  const altList = Array.isArray(srcs) ? alts || [] : [alt];
  const className = ["vc-fig", `vc-fig--${variant}`, card && "vc-fig--card"]
    .filter(Boolean)
    .join(" ");
  return (
    <figure
      className={className}
      style={maxWidth != null ? { maxWidth } : undefined}
    >
      <div className="vc-fig__media">
        {sources.map((s, i) => {
          const image = (
            <FigImage
              src={s}
              alt={altList[i]}
              enlarge={enlarge}
              maxHeight={maxHeight}
            />
          );
          if (variant !== "pair") {
            return <React.Fragment key={i}>{image}</React.Fragment>;
          }
          return (
            <div key={i} className="vc-fig__cell">
              {image}
              {subCaptions && subCaptions[i] ? (
                <div className="vc-fig__sub">
                  {renderCaption(subCaptions[i], `sub${i}`)}
                </div>
              ) : null}
            </div>
          );
        })}
      </div>
      {caption ? (
        <figcaption className="vc-fig__caption">
          {renderCaption(caption, "cap")}
        </figcaption>
      ) : null}
    </figure>
  );
}
