name: fibers-dataset
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - tifffile
  - scipy
  - tqdm
  - scikit-image
  - pip
  - pip:
      - webknossos==0.16.2
      - vesuvius
      - kimimaro
      - connected-components-3d
      - posix_ipc
