# config.yaml

# required:
input_store: "/home/giorgio/scrolls/scroll1/volumes/UV.zarr"
input_store_normal: "/home/giorgio/scrolls/scroll1/volumes/N.zarr"
output: "/home/giorgio/scrolls/scroll1/volumes/optim.zarr"
chunk: "128,128,128"

# penalties and hyperparams:
mu0: 1e-2
mu1: 1e-4
mu4: 1e-4
mu5: 1e-5
decay_max: 0.5
grad_clip: 0.5
optimizer_type: "adam"
init_type: "svd"
lr: 1.0
iters: 2000
ghost: 8
device: "cuda"

# optional labels‐overlay:
labels_store: "/home/giorgio/scrolls/scroll1/volumes/surfaces_2down.zarr"
skip: 5
viz_every: 1

# wandb logging controls:
log_iter_every: 20
log_patch_every: 1
wandb_project: "optimize_fields_viz"
