#pragma once

#include <array>
#include <filesystem>
#include <memory>
#include <mutex>
#include <vector>
#include "utils/Json.hpp"
#include <opencv2/core.hpp>

#include "vc/core/types/Sampling.hpp"
#include "vc/core/types/SampleParams.hpp"
#include "vc/core/util/RemoteAuth.hpp"

// Forward declarations
namespace vc { class VcDataset; }

namespace vc::render { class ChunkCache; class IChunkedArray; }

struct CompositeParams;

class Volume
{
public:
    // Static flag to skip zarr shape validation against meta.json
    static inline thread_local bool skipShapeCheck = false;

    Volume() = delete;

    explicit Volume(std::filesystem::path path);
    struct RemoteConstructTag {};
    Volume(std::filesystem::path path, RemoteConstructTag);

    ~Volume() noexcept;


    static std::shared_ptr<Volume> New(std::filesystem::path path);

    // Create a Volume backed by a remote zarr store over HTTP.
    // If auth is provided, it is used as-is; otherwise credentials are read
    // from environment variables. cacheRoot is currently ignored.
    static std::shared_ptr<Volume> NewFromUrl(
        const std::string& url,
        const std::filesystem::path& cacheRoot = {},
        const vc::HttpAuth& auth = {});

    [[nodiscard]] bool isRemote() const noexcept { return isRemote_; }
    [[nodiscard]] std::string id() const;
    [[nodiscard]] std::string name() const;
    [[nodiscard]] const std::string& remoteUrl() const noexcept { return remoteUrl_; }
    [[nodiscard]] const vc::HttpAuth& remoteAuth() const noexcept { return remoteAuth_; }
    [[nodiscard]] std::filesystem::path path() const noexcept { return path_; }

    [[nodiscard]] int sliceWidth() const noexcept;
    [[nodiscard]] int sliceHeight() const noexcept;
    [[nodiscard]] int numSlices() const noexcept;
    [[nodiscard]] std::array<int, 3> shape() const noexcept;
    [[nodiscard]] double voxelSize() const;

    [[nodiscard]] vc::VcDataset *zarrDataset(int level = 0) const;
    [[nodiscard]] size_t numScales() const noexcept;
    [[nodiscard]] int baseScaleLevel() const noexcept { return 0; }

    // --- Cache management ---

    [[nodiscard]] vc::render::IChunkedArray* chunkedCache();

    // Set cache budget for the chunked sampling cache.
    void setCacheBudget(size_t hotBytes);

    // Set the number of background IO threads for chunk fetching.
    void setIOThreads(int count);

    // --- Sampling API ---

    // Single-slice blocking sample (uint8)
    void sample(cv::Mat_<uint8_t>& out,
                const cv::Mat_<cv::Vec3f>& coords,
                const vc::SampleParams& params);

    // Single-slice blocking sample (uint16)
    void sample(cv::Mat_<uint16_t>& out,
                const cv::Mat_<cv::Vec3f>& coords,
                const vc::SampleParams& params);

    [[nodiscard]] static bool checkDir(const std::filesystem::path& path);

protected:
    std::filesystem::path path_;
    utils::Json metadata_;
    bool metadataAutoGenerated_{false};

    int _width{0};
    int _height{0};
    int _slices{0};

    std::vector<std::unique_ptr<vc::VcDataset>> zarrDs_;
    void zarrOpen();

    // Cache ownership
    mutable std::unique_ptr<vc::render::ChunkCache> chunkedCache_;
    mutable std::mutex cacheMutex_;
    size_t cacheBudgetHot_ = 8ULL << 30;   // 8 GB default
    int ioThreads_ = 0;  // 0 = use default

    void loadMetadata();

    // Remote volume state
    bool isRemote_ = false;
    std::string remoteUrl_;
    vc::HttpAuth remoteAuth_;
    size_t remoteNumScales_ = 0;
};
