tr_config:
  patch_size: [128,128,128]

model_config:
  architecture_type: "primus_m"

dataset_config:
  min_labeled_ratio: 0
  min_bbox_percent: 0
  normalization_scheme: "zscore"
  skip_patch_validation: true



