# LeJEPA pretraining configuration with Primus-M encoder
# Uses SIGReg (Sketched Isotropic Gaussian Regularization) for unsupervised learning

# Placeholder target for compatibility with base trainer
# (LeJEPA is self-supervised and doesn't use traditional targets)
targets:
  lejepa:
    activation: none
    weight: 1.0

tr_config:
  patch_size: [128, 128, 128]  # D, H, W - must be divisible by patch_embed_size
  initial_lr: 5e-4
  weight_decay: 0.05
  max_epoch: 100
  warmup_duration: 1  # 1 epoch warmup (matching original LeJEPA paper)

model_config:
  architecture_type: "primus_m"
  patch_embed_size: [8, 8, 8]  # Patch size for ViT embedding
  drop_path_rate: 0.1
  proj_drop_rate: 0.0
  attn_drop_rate: 0.0
  patch_drop_rate: 0.0  # No masking for LeJEPA

# LeJEPA-specific parameters
lejepa_config:
  lambda: 0.02  # Balance between invariance and SIGReg loss (original paper uses 0.02)
  num_global_views: 2  # Views with lighter augmentation (full resolution)
  num_local_views: 6  # Views with stronger augmentation (cropped + resized)
  sigreg_num_slices: 256  # Random projection directions for SIGReg
  proj_dim: 128  # Projection dimension (128-512 range recommended)
  local_crop_size: [64, 64, 64]  # Size for local view crops (multi-scale)
  primus_variant: "M"  # S, B, M, or L

dataset_config:
  min_labeled_ratio: 0          # No minimum labeled voxel ratio
  min_bbox_percent: 0           # No bounding box coverage requirement
  skip_patch_validation: false  # Validate patches (now works with image-only)
  allow_unlabeled_data: true    # Accept volumes without labels
  normalization_scheme: "zscore"  # z-score normalization per volume

  # Filter out blank/empty patches using image intensity
  unlabeled_foreground_enabled: true
  unlabeled_foreground_threshold: 0.1      # Min 10% non-zero voxels
  unlabeled_foreground_bbox_threshold: 0.1  # Min 10% bbox coverage
  valid_patch_find_resolution: 2           # Use zarr level 2 (4x downsample) for faster validation
