tr_setup:
  model_name: "ps128_guided_direct_segmentation_ink"

tr_config:
  patch_size: [128, 128, 128]
  batch_size: 1
  enable_deep_supervision: false
  guide_loss_weight: 0.0

model_config:
  guide_backbone: "/home/giorgio/Projects/dino-vesuvius/dino-checkpoints/checkpoint_step_342500.pt"
  guide_fusion_stage: "direct_segmentation"
  guide_compile_policy: "all_guidance"
  guide_freeze: true
  input_shape: [128, 128, 128]

dataset_config:
  min_labeled_ratio: 0.01
  min_bbox_percent: 0.15
  skip_patch_validation: false
  normalization_scheme: "zscore"
  ome_zarr_resolution: 0
  bg_sampling_enabled: true
  bg_to_fg_ratio: 0.10

  targets:
    ink:
      out_channels: 2
      activation: "none"
      ignore_label: 2
      losses:
        - name: "nnUNet_DC_and_CE_loss"
          weight: 1.0
