tr_config:
  patch_size: [512, 512]
  initial_lr: 0.0001

dataset_config:
  min_labeled_ratio: 0 
  min_bbox_percent: 0 
  normalization_scheme: "zscore"
  skip_patch_validation: true
  targets:
    ink:
      activation: "none"
      out_channels: 1
      losses:
        - name: "CEDiceLoss"
          weight: 1.0

