tr_config:
  patch_size: [1128, 128, 128]
  initial_lr: 0.01

dataset_config:
  min_labeled_ratio: 0 
  min_bbox_percent: 0 
  normalization_scheme: "zscore"
  skip_patch_validation: true
  targets:
    ink:
      activation: "none"
      out_channels: 1
      losses:
        - name: "BCEWithLogitsLoss"
          weight: 1.0
        - name: "SoftDiceLoss"
          weight: 1.0
          kwargs:
            smooth: 1e-5

