if(VC_PGO_GENERATE AND VC_PGO_USE)
    message(FATAL_ERROR "VC_PGO_GENERATE and VC_PGO_USE are mutually exclusive")
endif()

if(VC_PGO_GENERATE)
    file(MAKE_DIRECTORY "${VC_PGO_PROFILE_DIR}")
    message(STATUS "PGO instrumentation enabled — profile data → ${VC_PGO_PROFILE_DIR}")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        set(_pgo_flags "-fprofile-generate=${VC_PGO_PROFILE_DIR}")
    else()
        set(_pgo_flags "-fprofile-generate=${VC_PGO_PROFILE_DIR} -fprofile-update=atomic")
    endif()
    set(CMAKE_C_FLAGS            "${CMAKE_C_FLAGS} ${_pgo_flags}")
    set(CMAKE_CXX_FLAGS          "${CMAKE_CXX_FLAGS} ${_pgo_flags}")
    set(CMAKE_EXE_LINKER_FLAGS   "${CMAKE_EXE_LINKER_FLAGS} ${_pgo_flags}")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${_pgo_flags}")
endif()

if(VC_PGO_USE)
    if(NOT EXISTS "${VC_PGO_PROFILE_DIR}")
        message(FATAL_ERROR
            "VC_PGO_USE=ON but ${VC_PGO_PROFILE_DIR} does not exist. "
            "Build with VC_PGO_GENERATE=ON first, run the training workload, "
            "then reconfigure with VC_PGO_USE=ON.")
    endif()
    message(STATUS "PGO use enabled — consuming profile data from ${VC_PGO_PROFILE_DIR}")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        set(_pgo_flags "-fprofile-use=${VC_PGO_PROFILE_DIR}")
    else()
        set(_pgo_flags "-fprofile-use=${VC_PGO_PROFILE_DIR} -fprofile-correction")
    endif()
    set(CMAKE_C_FLAGS            "${CMAKE_C_FLAGS} ${_pgo_flags}")
    set(CMAKE_CXX_FLAGS          "${CMAKE_CXX_FLAGS} ${_pgo_flags}")
    set(CMAKE_EXE_LINKER_FLAGS   "${CMAKE_EXE_LINKER_FLAGS} ${_pgo_flags}")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${_pgo_flags}")
endif()
