from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import shutil
from typing import Mapping

from .config import atomic_write_text


def canonical_executable(argv0: str) -> Path:
    """Return the stable external command identity used by install and dispatch."""
    candidate = Path(argv0).expanduser()
    if not candidate.is_absolute():
        found = shutil.which(argv0)
        if found is None:
            raise ValueError(f"cannot resolve executable {argv0!r} from PATH")
        candidate = Path(found)
    if candidate.name != "las_manager":
        raise ValueError(
            "completion installation requires the installed las_manager console script; "
            "invoke las_manager directly instead of python -m"
        )
    resolved = candidate.resolve()
    if not resolved.is_file() or not os.access(resolved, os.X_OK):
        raise ValueError(
            "completion installation requires the installed las_manager console script; "
            "invoke las_manager directly instead of python -m"
        )
    return resolved


def provider_id(executable: Path) -> str:
    return hashlib.sha256(str(executable.resolve()).encode("utf-8")).hexdigest()[:20]


def _data_home() -> Path:
    configured = os.environ.get("XDG_DATA_HOME")
    if configured:
        return Path(os.path.expandvars(configured)).expanduser().resolve()
    return (Path.home() / ".local" / "share").resolve()


def _load_registry(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"invalid completion provider registry {path}: {error}") from error
    if not isinstance(raw, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in raw.items()):
        raise ValueError(f"invalid completion provider registry {path}: expected string mapping")
    return dict(raw)


def _dispatcher_script(providers: Mapping[str, str], provider_dir: Path) -> str:
    lines = [
        "# Generated by las_manager completion install; do not edit.",
    ]
    for identity in sorted(providers):
        provider_path = provider_dir / f"{identity}.bash"
        lines.append(f"[[ -r {shlex_quote(str(provider_path))} ]] && source {shlex_quote(str(provider_path))}")
    lines.extend([
        "_las_manager_completion_dispatch() {",
        "  local executable identity",
        "  executable=\"$(type -P las_manager 2>/dev/null)\" || return 0",
        "  [[ -n \"$executable\" && -f \"$executable\" && -x \"$executable\" ]] || return 0",
        "  identity=\"$(\"$executable\" _completion-provider-id 2>/dev/null)\" || return 0",
        "  case \"$identity\" in",
    ])
    for identity in sorted(providers):
        lines.append(f"    {identity}) _las_manager_complete_{identity} \"$@\" ;;")
    lines.extend([
        "  esac",
        "}",
        "complete -F _las_manager_completion_dispatch las_manager",
        "",
    ])
    return "\n".join(lines)


def shlex_quote(value: str) -> str:
    # Kept local so generated shell text has one auditable quoting boundary.
    import shlex

    return shlex.quote(value)


def install_bash_completion(executable: Path, provider_script: str) -> Path:
    executable = executable.resolve()
    identity = provider_id(executable)
    data_home = _data_home()
    root = data_home / "las_manager" / "completions" / "bash"
    provider_dir = root / "providers"
    registry_path = root / "providers.json"
    loader_path = data_home / "bash-completion" / "completions" / "las_manager"

    providers = _load_registry(registry_path)
    providers[identity] = str(executable)
    atomic_write_text(provider_dir / f"{identity}.bash", provider_script.rstrip() + "\n")
    atomic_write_text(registry_path, json.dumps(providers, indent=2, sort_keys=True) + "\n")
    atomic_write_text(loader_path, _dispatcher_script(providers, provider_dir))
    return loader_path
