# Minimal configuration for 2-class segmentation with labels 1 and 2
# Uses defaults for all optional parameters

tr_setup:
  model_name: TwoClass_Segmentation  # required field

tr_config:
  patch_size: [128, 128, 128]  # 3D patch size for patch extraction [z, y, x]

dataset_config:
  min_labeled_ratio: 0.1
  min_bbox_percent: 0.5
  targets:
    fibers:
      out_channels: 3
      activation: "none"
      weight: 1
      losses:
        - name: "nnUNet_DC_and_CE_loss"
          weight: 1.0
          kwargs: {}

inference_config:
  targets:
    - fibers:
        channels: 3  # 3 channels for background (0), class 1, and class 2
        activation: "softmax"
        weight: 1
