tr_setup:
  model_name: MultiTask_Fiber_Segmentation

tr_config:
  patch_size: [192, 192, 192]
  max_steps_per_epoch: 5000
  batch_size: 2

dataset_config:
  binarize_labels: true
  target_value:
    hz: 1  # Binary task
    vt: 1  # Binary task
  min_labeled_ratio: 0
  min_bbox_percent: 0
  skip_patch_validation: true
  targets:
    hz:
      activation: "none"
      weight: 1
      losses:
        - name: "CEDiceLoss"
          weight: 1.0
          kwargs: {}
    vt:
      activation: "none"
      weight: 1
      losses:
        - name: "CEDiceLoss"
          weight: 1.0
          kwargs: {}
  
  # Optional: Volume-task loss configuration
  # Specify which tasks should compute loss for which volumes
  # If not specified, all tasks compute loss on all volumes
  # volume_task_loss_config:
  #   image1: ["hz", "vt"]  # Both tasks enabled for image1
  #   image2: ["vt"]        # Only vt task enabled for image2
  #   image3: ["hz"]        # Only hz task enabled for image3
