tr_config:
  patch_size: [128,128,128]

dataset_config:
  min_labeled_ratio: 0 
  min_bbox_percent: 0 
  normalization_scheme: "zscore"
  skip_patch_validation: true
  targets:
    surface:
      activation: "none"
      out_channels: 1
      losses:
        - name: "nnUNet_DC_and_CE_loss"
          weight: 1.0

