name: vc-evaluation
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pandas
  - cupy
  - numpy
  - tifffile
  - wandb[media]
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  - pytorch
  - scikit-learn
  - torchvision
  - torchaudio
  - pip:
      - ./deps/scikit_image-0.24.1rc0.dev0-cp312-cp312-linux_x86_64.whl
      - kimimaro
      - posix-ipc
