name: vc-evaluation
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pandas
  - numpy
  - tifffile
  - wandb[media]
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - kimimaro
      - posix-ipc
