#include "vc/core/types/Volume.hpp"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <limits>
#include <mutex>
#include <optional>
#include <thread>

#ifdef __aarch64__
#include <arm_neon.h>
#endif

#include <opencv2/imgcodecs.hpp>
#include "vc/core/util/LoadJson.hpp"
#include "vc/core/util/Slicing.hpp"
#include "vc/core/cache/TieredChunkCache.hpp"
#include "vc/core/cache/ChunkSource.hpp"
#include "vc/core/cache/VcDecompressor.hpp"
#include <utils/zarr.hpp>
#include "vc/core/cache/HttpMetadataFetcher.hpp"
#include "vc/core/util/RemoteUrl.hpp"
#include "vc/core/util/NetworkFilesystem.hpp"
#include "vc/core/util/PostProcess.hpp"
#include "vc/core/types/VcDataset.hpp"

static const std::filesystem::path METADATA_FILE = "meta.json";
static const std::filesystem::path METADATA_FILE_ALT = "metadata.json";

Volume::Volume(std::filesystem::path path) : path_(std::move(path))
{
    loadMetadata();

    _width = metadata_["width"].get_int();
    _height = metadata_["height"].get_int();
    _slices = metadata_["slices"].get_int();

    zarrOpen();
    mountInfo_ = vc::detectNetworkMount(path_);
}

Volume::~Volume() noexcept
{
    // Request stop and join the prefetch thread before destroying the cache
    prefetchStop_.store(true, std::memory_order_relaxed);
}

void Volume::loadMetadata()
{
    metadataAutoGenerated_ = false;

    auto metaPath = path_ / METADATA_FILE;
    if (std::filesystem::exists(metaPath)) {
        metadata_ = vc::json::load_json_file(metaPath);
    } else if (std::filesystem::exists(path_ / METADATA_FILE_ALT)) {
        auto altPath = path_ / METADATA_FILE_ALT;
        auto full = vc::json::load_json_file(altPath);
        if (!full.contains("scan")) {
            throw std::runtime_error(
                "metadata.json missing 'scan' key: " + altPath.string());
        }
        metadata_ = full["scan"];
        if (!metadata_.contains("format")) {
            metadata_["format"] = "zarr";
        }
        metaPath = altPath;
    } else {
        const auto baseName = path_.filename().string();
        metadata_["uuid"] = baseName;
        metadata_["name"] = baseName;
        metadata_["type"] = "vol";
        metadata_["format"] = "zarr";
        metadata_["width"] = 0;
        metadata_["height"] = 0;
        metadata_["slices"] = 0;
        metadata_["voxelsize"] = double{};
        metadata_["min"] = double{};
        metadata_["max"] = double{};
        metadataAutoGenerated_ = true;
        return;
    }
    vc::json::require_type(metadata_, "type", "vol", metaPath.string());
    vc::json::require_fields(metadata_, {"uuid", "width", "height", "slices"}, metaPath.string());
}

std::string Volume::id() const
{
    return metadata_["uuid"].get_string();
}

std::string Volume::name() const
{
    return metadata_["name"].get_string();
}

bool Volume::checkDir(const std::filesystem::path& path)
{
    return std::filesystem::is_directory(path) &&
           (std::filesystem::exists(path / METADATA_FILE) ||
            std::filesystem::exists(path / METADATA_FILE_ALT) ||
            std::filesystem::exists(path / ".zgroup") ||
            std::filesystem::exists(path / ".zattrs"));
}

static int ceilDivPow2(int v, int level)
{
    const int64_t denom = int64_t{1} << level;
    return static_cast<int>((static_cast<int64_t>(v) + denom - 1) / denom);
}

void Volume::zarrOpen()
{
    if (!metadata_.contains("format") || metadata_["format"].get_string() != "zarr")
        return;

    zarrDs_ = vc::openZarrLevels(path_);

    for (size_t i = 0; i < zarrDs_.size(); i++) {
        auto dtype = zarrDs_[i]->getDtype();
        if (dtype != vc::VcDtype::uint8 && dtype != vc::VcDtype::uint16)
            throw std::runtime_error("only uint8 & uint16 is currently supported for zarr datasets, incompatible type found in " + path_.string());
    }

    if (metadataAutoGenerated_) {

        bool hasReference = false;
        int baseSlices = 0;
        int baseHeight = 0;
        int baseWidth = 0;

        for (size_t level = 0; level < zarrDs_.size(); ++level) {
            const auto& ds = zarrDs_[level];
            if (!ds) {
                continue;
            }

            const auto& shape = ds->shape();
            const int levelInt = static_cast<int>(level);

            if (!hasReference) {
                const size_t scale = size_t{1} << levelInt;
                baseSlices = static_cast<int>(shape[0] * scale);
                baseHeight = static_cast<int>(shape[1] * scale);
                baseWidth = static_cast<int>(shape[2] * scale);
                hasReference = true;
            }

            const int expectedSlices = ceilDivPow2(baseSlices, levelInt);
            const int expectedHeight = ceilDivPow2(baseHeight, levelInt);
            const int expectedWidth = ceilDivPow2(baseWidth, levelInt);

            if (static_cast<int>(shape[0]) != expectedSlices ||
                static_cast<int>(shape[1]) != expectedHeight ||
                static_cast<int>(shape[2]) != expectedWidth) {
                throw std::runtime_error(
                    "zarr level " + std::to_string(levelInt) + " shape [z,y,x]=("
                    + std::to_string(shape[0]) + ", " + std::to_string(shape[1]) + ", " + std::to_string(shape[2])
                    + ") does not match synthesized dimensions from first found scale (slices=" + std::to_string(baseSlices)
                    + ", height=" + std::to_string(baseHeight) + ", width=" + std::to_string(baseWidth)
                    + ") in " + path_.string());
            }
        }

        if (!hasReference) {
            throw std::runtime_error("no physical zarr dataset directories found in " + path_.string());
        }

        _slices = baseSlices;
        _height = baseHeight;
        _width = baseWidth;
        metadata_["slices"] = _slices;
        metadata_["height"] = _height;
        metadata_["width"] = _width;
    }

    // Verify each existing level shape against meta.json dimensions and level downscale.
    // zarr shape is [z, y, x] = [slices, height, width]
    if (!skipShapeCheck) {
        bool hasAnyPhysicalScale = false;
        for (size_t level = 0; level < zarrDs_.size(); ++level) {
            const auto& ds = zarrDs_[level];
            if (!ds) {
                continue;
            }
            hasAnyPhysicalScale = true;

            const auto& shape = ds->shape();
            const int expectedSlices = ceilDivPow2(_slices, static_cast<int>(level));
            const int expectedHeight = ceilDivPow2(_height, static_cast<int>(level));
            const int expectedWidth = ceilDivPow2(_width, static_cast<int>(level));

            if (static_cast<int>(shape[0]) != expectedSlices ||
                static_cast<int>(shape[1]) != expectedHeight ||
                static_cast<int>(shape[2]) != expectedWidth) {
                throw std::runtime_error(
                    "zarr level " + std::to_string(level) + " shape [z,y,x]=("
                    + std::to_string(shape[0]) + ", " + std::to_string(shape[1]) + ", " + std::to_string(shape[2])
                    + ") does not match expected downscaled meta.json dimensions (slices=" + std::to_string(expectedSlices)
                    + ", height=" + std::to_string(expectedHeight) + ", width=" + std::to_string(expectedWidth)
                    + ") in " + path_.string());
            }
        }

        if (!hasAnyPhysicalScale) {
            throw std::runtime_error("no physical zarr dataset directories found in " + path_.string());
        }
    }
}

std::shared_ptr<Volume> Volume::New(std::filesystem::path path)
{
    return std::make_shared<Volume>(std::move(path));
}

std::shared_ptr<Volume> Volume::NewFromUrl(
    const std::string& url,
    const std::filesystem::path& cacheRoot,
    const vc::cache::HttpAuth& authIn)
{
    namespace fs = std::filesystem;

    // Resolve s3:// URLs to https:// and detect AWS credentials
    auto resolved = vc::resolveRemoteUrl(url);
    vc::cache::HttpAuth auth = authIn;
    if (resolved.useAwsSigv4 && auth.empty()) {
        auth = vc::cache::loadAwsCredentials();
        if (auth.region.empty())
            auth.region = resolved.awsRegion;
    } else if (resolved.useAwsSigv4 && auth.region.empty()) {
        auth.region = resolved.awsRegion;
    }

    // Determine cache root
    fs::path root = cacheRoot;
    if (root.empty()) {
        root = fs::path(std::getenv("HOME") ? std::getenv("HOME") : "/tmp") / ".VC3D" / "remote_cache";
    }

    // Fetch remote metadata (downloads .zarray files, synthesizes meta.json)
    auto info = vc::cache::fetchRemoteZarrMetadata(resolved.httpsUrl, root, auth);

    // Temporarily skip shape validation (staging dir has no chunk data)
    struct SkipShapeGuard {
        bool prev;
        SkipShapeGuard() : prev(skipShapeCheck) { skipShapeCheck = true; }
        ~SkipShapeGuard() { skipShapeCheck = prev; }
    };
    SkipShapeGuard guard;

    auto vol = std::make_shared<Volume>(info.stagingDir);

    vol->isRemote_ = true;
    vol->remoteUrl_ = info.url;
    vol->remoteDelimiter_ = info.delimiter;
    vol->remoteAuth_ = auth;
    vol->remoteShardConfig_ = info.shardConfig;

    return vol;
}

int Volume::sliceWidth() const noexcept { return _width; }
int Volume::sliceHeight() const noexcept { return _height; }
int Volume::numSlices() const noexcept { return _slices; }
std::array<int, 3> Volume::shape() const noexcept { return {_width, _height, _slices}; }
double Volume::voxelSize() const
{
    return metadata_["voxelsize"].get_double();
}

vc::VcDataset *Volume::zarrDataset(int level) const {
    if (level < 0 || zarrDs_.empty())
        return nullptr;

    if (static_cast<size_t>(level) >= zarrDs_.size())
        return nullptr;

    return zarrDs_[static_cast<size_t>(level)].get();
}

size_t Volume::numScales() const noexcept {
    return zarrDs_.size();
}

std::unique_ptr<vc::cache::TieredChunkCache> Volume::createTieredCache(
    std::shared_ptr<utils::ZarrArray> diskZarr) const
{
    if (zarrDs_.empty()) return nullptr;

    // Build level metadata from our zarr datasets
    std::vector<vc::cache::FileSystemChunkSource::LevelMeta> levels;
    levels.reserve(zarrDs_.size());
    for (auto& ds : zarrDs_) {
        const auto& shape = ds->shape();
        const auto& chunks = ds->defaultChunkShape();
        vc::cache::FileSystemChunkSource::LevelMeta lm;
        lm.shape = {
            static_cast<int>(shape[0]),
            static_cast<int>(shape[1]),
            static_cast<int>(shape[2])};
        lm.chunkShape = {
            static_cast<int>(chunks[0]),
            static_cast<int>(chunks[1]),
            static_cast<int>(chunks[2])};
        levels.push_back(lm);
    }

    // Get delimiter from VcDataset
    std::string delimiter = zarrDs_[0]->delimiter();

    // Create chunk source: HTTP for remote volumes, filesystem for local
    std::unique_ptr<vc::cache::ChunkSource> source;
    if (isRemote_) {
        auto httpSource = std::make_unique<vc::cache::HttpChunkSource>(
            remoteUrl_, remoteDelimiter_, std::move(levels), remoteAuth_);
        if (remoteShardConfig_.enabled) {
            httpSource->setShardConfig(remoteShardConfig_);
        }
        source = std::move(httpSource);

        // Create or open a canonical zarr v3 sharded cold cache.
        // 128³ chunks in 1024³ shards, no codec (data is already H.265 compressed).
        if (!diskZarr) {
            auto zarrPath = path_ / "cache";
            try {
                if (std::filesystem::exists(zarrPath / "zarr.json")) {
                    diskZarr = std::make_shared<utils::ZarrArray>(
                        utils::ZarrArray::open(zarrPath));
                } else {
                    // Get level 0 shape from source metadata
                    auto l0shape = source->levelShape(0);
                    utils::ZarrMetadata meta;
                    meta.version = utils::ZarrVersion::v3;
                    meta.node_type = "array";
                    meta.shape = {static_cast<size_t>(l0shape[0]),
                                  static_cast<size_t>(l0shape[1]),
                                  static_cast<size_t>(l0shape[2])};
                    meta.chunks = {1024, 1024, 1024};  // shard shape
                    meta.dtype = utils::ZarrDtype::uint8;
                    meta.fill_value = 0;
                    meta.chunk_key_encoding = "default";
                    utils::ShardConfig sc;
                    sc.sub_chunks = {128, 128, 128};   // inner chunk shape
                    sc.index_at_end = false;  // index at start for append-only writes
                    meta.shard_config = std::move(sc);
                    diskZarr = std::make_shared<utils::ZarrArray>(
                        utils::ZarrArray::create(zarrPath, std::move(meta)));
                }
                fprintf(stderr, "[Volume] Cold cache: %s (sharded=%s)\n",
                        zarrPath.c_str(), diskZarr->is_sharded() ? "yes" : "no");
            } catch (const std::exception& e) {
                fprintf(stderr, "[Volume] Failed to create cold cache: %s\n", e.what());
            }
        }
    } else {
        source = std::make_unique<vc::cache::FileSystemChunkSource>(
            path_, delimiter, std::move(levels));

        // Auto-enable disk caching for network-mounted volumes
        if (!diskZarr && mountInfo_.type == vc::FilesystemType::NetworkMount) {
            if (!mountInfo_.cacheDir.empty()) {
                fprintf(stderr, "[Volume] Detected %s mount with use_cache=%s; "
                                "skipping app-level disk cache\n",
                        mountInfo_.label.c_str(),
                        mountInfo_.cacheDir.c_str());
            } else {
                namespace fs = std::filesystem;
                auto home = std::getenv("HOME");
                auto zarrPath = fs::path(home ? home : "/tmp") / ".VC3D" / "network_cache" / id() / "cache";
                try {
                    if (fs::exists(zarrPath / "zarr.json")) {
                        diskZarr = std::make_shared<utils::ZarrArray>(
                            utils::ZarrArray::open(zarrPath));
                    } else {
                        auto l0shape = source->levelShape(0);
                        utils::ZarrMetadata meta;
                        meta.version = utils::ZarrVersion::v3;
                        meta.node_type = "array";
                        meta.shape = {static_cast<size_t>(l0shape[0]),
                                      static_cast<size_t>(l0shape[1]),
                                      static_cast<size_t>(l0shape[2])};
                        meta.chunks = {1024, 1024, 1024};
                        meta.dtype = utils::ZarrDtype::uint8;
                        meta.fill_value = 0;
                        meta.chunk_key_encoding = "default";
                        utils::ShardConfig sc;
                        sc.sub_chunks = {128, 128, 128};
                        sc.index_at_end = false;  // index at start for append-only writes
                        meta.shard_config = std::move(sc);
                        diskZarr = std::make_shared<utils::ZarrArray>(
                            utils::ZarrArray::create(zarrPath, std::move(meta)));
                    }
                    fprintf(stderr, "[Volume] Network cold cache: %s\n", zarrPath.c_str());
                } catch (const std::exception& e) {
                    fprintf(stderr, "[Volume] Failed to create network cold cache: %s\n", e.what());
                }
            }
        }
    }

    // Build dataset pointers for the decompressor
    std::vector<vc::VcDataset*> dsPtrs;
    dsPtrs.reserve(zarrDs_.size());
    for (auto& ds : zarrDs_) {
        dsPtrs.push_back(ds.get());
    }
    auto decompress = vc::cache::makeVcDecompressor(dsPtrs);

    vc::cache::TieredChunkCache::Config config;
    config.volumeId = id();
    config.hotMaxBytes = cacheBudgetHot_;
    if (isRemote_ || mountInfo_.type == vc::FilesystemType::NetworkMount) {
        if (ioThreads_ > 0) {
            config.ioThreads = ioThreads_;
        } else if (mountInfo_.parallelCount > 0) {
            config.ioThreads = mountInfo_.parallelCount;
        } else {
            config.ioThreads = 8;  // HTTP/2 multiplexing: fewer connections, many streams each
        }
        fprintf(stderr, "[Volume] IO threads: %d\n", config.ioThreads);
    }

    return std::make_unique<vc::cache::TieredChunkCache>(
        std::move(config),
        std::move(source),
        std::move(decompress),
        std::move(diskZarr));
}

// ============================================================================
// Cache management
// ============================================================================

void Volume::ensureTieredCache() const
{
    std::call_once(cacheOnce_, [this]() {
        auto* self = const_cast<Volume*>(this);
        tieredCache_ = self->createTieredCache(self->pendingDiskZarr_);
    });
}

vc::cache::TieredChunkCache* Volume::tieredCache()
{
    ensureTieredCache();
    return tieredCache_.get();
}

void Volume::setCacheBudget(size_t hotBytes)
{
    cacheBudgetHot_ = hotBytes;
}

void Volume::setDiskZarr(std::shared_ptr<utils::ZarrArray> zarr)
{
    if (tieredCache_) {
        fprintf(stderr, "[Volume] WARNING: setDiskZarr() called after cache "
                        "already created — ignoring\n");
        return;
    }
    pendingDiskZarr_ = std::move(zarr);
}

void Volume::setDiskCacheMaxBytes(size_t bytes)
{
    diskCacheMaxBytes_ = bytes;
}

void Volume::setIOThreads(int count)
{
    ioThreads_ = count;
}

// ============================================================================
// Sampling API
// ============================================================================

// Helper: apply optional post-processing from SampleParams in-place.
static void applyOptionalPostProcess(cv::Mat_<uint8_t>& img,
                                     const vc::SampleParams& params)
{
    if (!params.postProcess) return;
    vc::applyPostProcess(img, *params.postProcess);
}

// Helper: scale level-0 coords to pyramid level coords.
static const cv::Mat_<cv::Vec3f>& scaleCoords(const cv::Mat_<cv::Vec3f>& coords, int level)
{
    if (level <= 0) return coords;
    // Thread-local buffer avoids per-tile allocation for the scaled copy
    thread_local cv::Mat_<cv::Vec3f> scaled;
    float scale = 1.0f / static_cast<float>(1 << level);
    if (scaled.rows != coords.rows || scaled.cols != coords.cols) {
        scaled.create(coords.size());
    }
    const int total = coords.rows * coords.cols;
    const auto* src = coords.ptr<cv::Vec3f>();
    auto* dst = scaled.ptr<cv::Vec3f>();
    for (int i = 0; i < total; ++i) {
        dst[i] = src[i] * scale;
    }
    return scaled;
}

void Volume::sample(cv::Mat_<uint8_t>& out,
                    const cv::Mat_<cv::Vec3f>& coords,
                    const vc::SampleParams& params)
{
    const auto& scaled = scaleCoords(coords, params.level);
    readInterpolated3D(out, tieredCache(), params.level, scaled, params.method);
    applyOptionalPostProcess(out, params);
}

void Volume::sample(cv::Mat_<uint16_t>& out,
                    const cv::Mat_<cv::Vec3f>& coords,
                    const vc::SampleParams& params)
{
    const auto& scaled = scaleCoords(coords, params.level);
    readInterpolated3D(out, tieredCache(), params.level, scaled, params.method);
}

int Volume::sampleBestEffort(cv::Mat_<uint8_t>& out,
                              const cv::Mat_<cv::Vec3f>& coords,
                              const vc::SampleParams& params)
{
    const int nScales = static_cast<int>(numScales());
    const int level = params.level;

    // Compute world-space bounding box once, reuse for all level checks.
    // This avoids re-scanning border/interior pixels per level.
    auto wb = coordsWorldBBox(coords);

    // Find best cached level without scaling coords each iteration.
    int useLvl = -1;
    for (int lvl = level; lvl < nScales; lvl++) {
        if (allChunksCachedFast(wb, lvl)) {
            useLvl = lvl;
            break;
        }
    }
    // No level had all chunks cached.  Fall back to the coarsest level
    // (which is pinned hot in steady state, so this only blocks during
    // initial loading).
    if (useLvl < 0)
        useLvl = std::max(0, nScales - 1);

    // Scale coords ONCE for the chosen level.
    const auto& scaled = scaleCoords(coords, useLvl);
    readInterpolated3D(out, tieredCache(), useLvl, scaled, params.method);

    if (useLvl > level) {
        // Prefetch desired level and one intermediate for progressive refinement
        prefetchChunks(coords, level);
        if (useLvl - level > 1)
            prefetchChunks(coords, level + 1);
    } else if (useLvl > 0) {
        // At desired level — prefetch next finer for smooth zoom-in
        prefetchChunks(coords, useLvl - 1);
    }
    if (!out.empty())
        applyOptionalPostProcess(out, params);
    return useLvl;
}

void Volume::sampleComposite(cv::Mat_<uint8_t>& out,
                              const cv::Mat_<cv::Vec3f>& coords,
                              const cv::Mat_<cv::Vec3f>& normals,
                              const vc::SampleParams& params)
{
    float scale = (params.level > 0) ? (1.0f / static_cast<float>(1 << params.level)) : 1.0f;
    const auto& scaled = scaleCoords(coords, params.level);
    readCompositeFast(out, tieredCache(), params.level, scaled, normals, scale,
                      params.zStart, params.zEnd,
                      params.composite.value_or(CompositeParams{}),
                      params.method);
    applyOptionalPostProcess(out, params);
}

int Volume::sampleCompositeBestEffort(cv::Mat_<uint8_t>& out,
                                       const cv::Mat_<cv::Vec3f>& coords,
                                       const cv::Mat_<cv::Vec3f>& normals,
                                       const vc::SampleParams& params)
{
    const int nScales = static_cast<int>(numScales());
    const int level = params.level;
    const auto& cp = params.composite.value_or(CompositeParams{});

    for (int lvl = level; lvl < nScales; lvl++) {
        if (allCompositeChunksCached(coords, normals, params.zStart, params.zEnd, lvl)) {
            // Render at this level
            vc::SampleParams lvlParams = params;
            lvlParams.level = lvl;
            sampleComposite(out, coords, normals, lvlParams);
            if (lvl > level)
                prefetchCompositeChunks(coords, normals, params.zStart, params.zEnd, level);
            return lvl;
        }
    }

    // Coarsest level — block
    int last = std::max(0, nScales - 1);
    vc::SampleParams lastParams = params;
    lastParams.level = last;
    sampleComposite(out, coords, normals, lastParams);
    if (last > level)
        prefetchCompositeChunks(coords, normals, params.zStart, params.zEnd, level);
    return last;
}

// Plane bounding box helper shared by samplePlaneBestEffort and ARGB32 variant.
// Uses a local struct identical to Volume::WorldBBox (which is protected).
struct PlaneBBox { float loX, loY, loZ, hiX, hiY, hiZ; };

static PlaneBBox planeBBox(const cv::Vec3f& origin,
                           const cv::Vec3f& vx_step,
                           const cv::Vec3f& vy_step,
                           int width, int height)
{
    cv::Vec3f corners[4] = {
        origin,
        origin + vx_step * static_cast<float>(width - 1),
        origin + vy_step * static_cast<float>(height - 1),
        origin + vx_step * static_cast<float>(width - 1) + vy_step * static_cast<float>(height - 1)
    };
    PlaneBBox wb;
    wb.loX = corners[0][0]; wb.hiX = corners[0][0];
    wb.loY = corners[0][1]; wb.hiY = corners[0][1];
    wb.loZ = corners[0][2]; wb.hiZ = corners[0][2];
    for (int c = 1; c < 4; c++) {
        wb.loX = std::min(wb.loX, corners[c][0]); wb.hiX = std::max(wb.hiX, corners[c][0]);
        wb.loY = std::min(wb.loY, corners[c][1]); wb.hiY = std::max(wb.hiY, corners[c][1]);
        wb.loZ = std::min(wb.loZ, corners[c][2]); wb.hiZ = std::max(wb.hiZ, corners[c][2]);
    }
    return wb;
}

int Volume::samplePlaneBestEffort(cv::Mat_<uint8_t>& out,
                                   const cv::Vec3f& origin,
                                   const cv::Vec3f& vx_step,
                                   const cv::Vec3f& vy_step,
                                   int width, int height,
                                   const vc::SampleParams& params)
{
    const int nScales = static_cast<int>(numScales());
    const int level = params.level;

    auto pb = planeBBox(origin, vx_step, vy_step, width, height);
    WorldBBox wb{pb.loX, pb.loY, pb.loZ, pb.hiX, pb.hiY, pb.hiZ};

    for (int lvl = level; lvl < nScales; lvl++) {
        if (allChunksCachedFast(wb, lvl)) {
            float scale = (lvl > 0) ? (1.0f / static_cast<float>(1 << lvl)) : 1.0f;
            samplePlane(out, tieredCache(), lvl,
                        origin * scale, vx_step * scale, vy_step * scale,
                        width, height, params.method);
            if (lvl > level) {
                prefetchWorldBBox(
                    cv::Vec3f(wb.loX, wb.loY, wb.loZ),
                    cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), level);
                if (lvl - level > 1)
                    prefetchWorldBBox(
                        cv::Vec3f(wb.loX, wb.loY, wb.loZ),
                        cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), level + 1);
            } else if (lvl > 0) {
                prefetchWorldBBox(
                    cv::Vec3f(wb.loX, wb.loY, wb.loZ),
                    cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), lvl - 1);
            }
            if (!out.empty())
                applyOptionalPostProcess(out, params);
            return lvl;
        }
    }

    // No level cached — block at coarsest level
    int last = std::max(0, nScales - 1);
    float scale = (last > 0) ? (1.0f / static_cast<float>(1 << last)) : 1.0f;
    samplePlane(out, tieredCache(), last,
                origin * scale, vx_step * scale, vy_step * scale,
                width, height, params.method);
    if (last > level) {
        prefetchWorldBBox(
            cv::Vec3f(wb.loX, wb.loY, wb.loZ),
            cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), level);
        if (last - level > 1)
            prefetchWorldBBox(
                cv::Vec3f(wb.loX, wb.loY, wb.loZ),
                cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), level + 1);
    }
    if (!out.empty())
        applyOptionalPostProcess(out, params);
    return last;
}

int Volume::samplePlaneBestEffortARGB32(uint32_t* outBuf, int outStride,
                                         const cv::Vec3f& origin,
                                         const cv::Vec3f& vx_step,
                                         const cv::Vec3f& vy_step,
                                         int width, int height,
                                         const vc::SampleParams& params,
                                         const uint32_t lut[256])
{
    const int nScales = static_cast<int>(numScales());
    const int level = params.level;

    auto pb = planeBBox(origin, vx_step, vy_step, width, height);
    WorldBBox wb{pb.loX, pb.loY, pb.loZ, pb.hiX, pb.hiY, pb.hiZ};

    for (int lvl = level; lvl < nScales; lvl++) {
        if (allChunksCachedFast(wb, lvl)) {
            float scale = (lvl > 0) ? (1.0f / static_cast<float>(1 << lvl)) : 1.0f;
            samplePlaneARGB32(outBuf, outStride, tieredCache(), lvl,
                              origin * scale, vx_step * scale, vy_step * scale,
                              width, height, params.method, lut);
            if (lvl > level) {
                prefetchWorldBBox(
                    cv::Vec3f(wb.loX, wb.loY, wb.loZ),
                    cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), level);
                if (lvl - level > 1)
                    prefetchWorldBBox(
                        cv::Vec3f(wb.loX, wb.loY, wb.loZ),
                        cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), level + 1);
            } else if (lvl > 0) {
                prefetchWorldBBox(
                    cv::Vec3f(wb.loX, wb.loY, wb.loZ),
                    cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), lvl - 1);
            }
            return lvl;
        }
    }

    // No level cached -- block at coarsest level
    int last = std::max(0, nScales - 1);
    float scale = (last > 0) ? (1.0f / static_cast<float>(1 << last)) : 1.0f;
    samplePlaneARGB32(outBuf, outStride, tieredCache(), last,
                      origin * scale, vx_step * scale, vy_step * scale,
                      width, height, params.method, lut);
    if (last > level) {
        prefetchWorldBBox(
            cv::Vec3f(wb.loX, wb.loY, wb.loZ),
            cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), level);
        if (last - level > 1)
            prefetchWorldBBox(
                cv::Vec3f(wb.loX, wb.loY, wb.loZ),
                cv::Vec3f(wb.hiX, wb.hiY, wb.hiZ), level + 1);
    }
    return last;
}

int Volume::samplePlaneCompositeBestEffortARGB32(
    uint32_t* outBuf, int outStride,
    const cv::Vec3f& origin, const cv::Vec3f& vx_step, const cv::Vec3f& vy_step,
    const cv::Vec3f& normal, float zStep, int zStart, int numLayers,
    int width, int height,
    const std::string& compositeMethod,
    const uint32_t lut[256])
{
    const int nScales = static_cast<int>(numScales());

    // Use same best-effort level selection as samplePlaneBestEffortARGB32.
    // The planeBBox needs to account for normal offsets.
    auto pb = planeBBox(origin, vx_step, vy_step, width, height);
    float minOff = static_cast<float>(zStart) * zStep;
    float maxOff = static_cast<float>(zStart + numLayers - 1) * zStep;
    if (minOff > maxOff) std::swap(minOff, maxOff);
    // Expand bbox along normal direction
    for (int a = 0; a < 3; a++) {
        float nMin = normal[a] * minOff;
        float nMax = normal[a] * maxOff;
        if (nMin > nMax) std::swap(nMin, nMax);
        (&pb.loX)[a] += nMin;
        (&pb.hiX)[a] += nMax;
    }
    WorldBBox wb{pb.loX, pb.loY, pb.loZ, pb.hiX, pb.hiY, pb.hiZ};

    int level = 0; // Always try finest first for composite
    for (int lvl = level; lvl < nScales; lvl++) {
        if (allChunksCachedFast(wb, lvl)) {
            float scale = (lvl > 0) ? (1.0f / static_cast<float>(1 << lvl)) : 1.0f;
            samplePlaneCompositeARGB32(outBuf, outStride, tieredCache(), lvl,
                origin * scale, vx_step * scale, vy_step * scale,
                normal, zStep, zStart, numLayers,
                width, height, compositeMethod, lut);
            return lvl;
        }
    }

    // Fallback: block at coarsest level
    int last = std::max(0, nScales - 1);
    float scale = (last > 0) ? (1.0f / static_cast<float>(1 << last)) : 1.0f;
    samplePlaneCompositeARGB32(outBuf, outStride, tieredCache(), last,
        origin * scale, vx_step * scale, vy_step * scale,
        normal, zStep, zStart, numLayers,
        width, height, compositeMethod, lut);
    return last;
}

// ============================================================================
// Composite-aware chunk helpers
// ============================================================================

namespace {
struct BBox6f {
    float loX, loY, loZ, hiX, hiY, hiZ;
};

BBox6f computeCompositeBBox(const cv::Mat_<cv::Vec3f>& coords,
                            const cv::Mat_<cv::Vec3f>& normals,
                            int zStart, int zEnd, int level)
{
    float scale = (level > 0) ? (1.0f / static_cast<float>(1 << level)) : 1.0f;

    float loX = std::numeric_limits<float>::max();
    float loY = std::numeric_limits<float>::max();
    float loZ = std::numeric_limits<float>::max();
    float hiX = std::numeric_limits<float>::lowest();
    float hiY = std::numeric_limits<float>::lowest();
    float hiZ = std::numeric_limits<float>::lowest();

    const bool hasNormals = !normals.empty() && normals.size() == coords.size();
    const int h = coords.rows;
    const int w = coords.cols;

    auto updateBounds = [&](int r, int c) {
        const auto& v = coords(r, c);
        float sx = v[0] * scale;
        float sy = v[1] * scale;
        float sz = v[2] * scale;

        cv::Vec3f n = hasNormals ? normals(r, c) : cv::Vec3f(1, 0, 0);
        for (int z : {zStart, zEnd}) {
            float off = static_cast<float>(z) * scale;
            float px = sx + n[0] * off;
            float py = sy + n[1] * off;
            float pz = sz + n[2] * off;
            loX = std::min(loX, px); hiX = std::max(hiX, px);
            loY = std::min(loY, py); hiY = std::max(hiY, py);
            loZ = std::min(loZ, pz); hiZ = std::max(hiZ, pz);
        }
    };

    // Sample border pixels + sparse grid instead of every pixel.
    // Top and bottom rows
    for (int c = 0; c < w; ++c) {
        updateBounds(0, c);
        updateBounds(h - 1, c);
    }
    // Left and right columns (excluding corners already covered)
    for (int r = 1; r < h - 1; ++r) {
        updateBounds(r, 0);
        updateBounds(r, w - 1);
    }
    // Sparse interior grid (every 32 pixels) to catch curved surfaces
    for (int r = 32; r < h - 1; r += 32) {
        for (int c = 32; c < w - 1; c += 32) {
            updateBounds(r, c);
        }
    }

    // 1-voxel margin for interpolation (plus extra for normal offset curvature)
    loX -= 2.0f; loY -= 2.0f; loZ -= 2.0f;
    hiX += 2.0f; hiY += 2.0f; hiZ += 2.0f;

    return {loX, loY, loZ, hiX, hiY, hiZ};
}
} // anonymous namespace

Volume::ChunkBBox Volume::compositeChunkBBox(
    const cv::Mat_<cv::Vec3f>& coords,
    const cv::Mat_<cv::Vec3f>& normals,
    int zStart, int zEnd, int level) const
{
    vc::VcDataset* ds = zarrDataset(level);
    if (!ds || coords.empty()) return {0, -1, 0, -1, 0, -1};  // invalid

    auto bb = computeCompositeBBox(coords, normals, zStart, zEnd, level);

    auto cs = ds->defaultChunkShape();  // {cz, cy, cx}
    const auto& shape = ds->shape();    // {z, y, x}
    float csX = static_cast<float>(cs[2]), csY = static_cast<float>(cs[1]), csZ = static_cast<float>(cs[0]);

    ChunkBBox cbbox;
    cbbox.minIx = std::max(0, static_cast<int>(std::floor(bb.loX / csX)));
    cbbox.maxIx = std::min(static_cast<int>(std::ceil(bb.hiX / csX)),
                           static_cast<int>((shape[2] - 1) / cs[2]));
    cbbox.minIy = std::max(0, static_cast<int>(std::floor(bb.loY / csY)));
    cbbox.maxIy = std::min(static_cast<int>(std::ceil(bb.hiY / csY)),
                           static_cast<int>((shape[1] - 1) / cs[1]));
    cbbox.minIz = std::max(0, static_cast<int>(std::floor(bb.loZ / csZ)));
    cbbox.maxIz = std::min(static_cast<int>(std::ceil(bb.hiZ / csZ)),
                           static_cast<int>((shape[0] - 1) / cs[0]));
    return cbbox;
}

bool Volume::allCompositeChunksCached(
    const cv::Mat_<cv::Vec3f>& coords,
    const cv::Mat_<cv::Vec3f>& normals,
    int zStart, int zEnd, int level) const
{
    ensureTieredCache();
    if (!tieredCache_ || coords.empty()) return false;

    auto cbbox = compositeChunkBBox(coords, normals, zStart, zEnd, level);
    if (cbbox.minIx > cbbox.maxIx || cbbox.minIy > cbbox.maxIy || cbbox.minIz > cbbox.maxIz)
        return false;

    return tieredCache_->areAllCachedInRegion(
        level, cbbox.minIz, cbbox.minIy, cbbox.minIx,
        cbbox.maxIz, cbbox.maxIy, cbbox.maxIx);
}

void Volume::prefetchCompositeChunks(
    const cv::Mat_<cv::Vec3f>& coords,
    const cv::Mat_<cv::Vec3f>& normals,
    int zStart, int zEnd, int level)
{
    ensureTieredCache();
    if (!tieredCache_ || coords.empty()) return;

    auto cbbox = compositeChunkBBox(coords, normals, zStart, zEnd, level);
    if (cbbox.minIx > cbbox.maxIx || cbbox.minIy > cbbox.maxIy || cbbox.minIz > cbbox.maxIz)
        return;

    tieredCache_->prefetchRegion(level, cbbox.minIz, cbbox.minIy, cbbox.minIx,
                                 cbbox.maxIz, cbbox.maxIy, cbbox.maxIx);
}

void Volume::pinCoarsestLevel(bool blocking)
{
    ensureTieredCache();
    if (!tieredCache_ || zarrDs_.empty()) return;

    int last = static_cast<int>(zarrDs_.size()) - 1;
    tieredCache_->loadCoarseLevel(last);

    // Scan the coarsest level for all-zero chunks and propagate
    // zero-knowledge to all finer levels. This eliminates network requests
    // for chunks in masked/padded regions of the volume.
    tieredCache_->propagateZeroChunks(last);
    if (blocking) {
        computeDataBounds();
    }
}

// ============================================================================
// Data bounds
// ============================================================================

void Volume::computeDataBounds()
{
    // Set bounds to the full volume shape — no scanning needed.
    dataBounds_.minX = 0;
    dataBounds_.maxX = _width - 1;
    dataBounds_.minY = 0;
    dataBounds_.maxY = _height - 1;
    dataBounds_.minZ = 0;
    dataBounds_.maxZ = _slices - 1;
    dataBounds_.valid = true;

    // Push to cache so ChunkSampler can skip chunks outside bounds
    ensureTieredCache();
    if (tieredCache_) {
        tieredCache_->setDataBounds(
            dataBounds_.minX, dataBounds_.maxX,
            dataBounds_.minY, dataBounds_.maxY,
            dataBounds_.minZ, dataBounds_.maxZ);
    }

    fprintf(stderr, "[Volume] dataBounds: x=[%d, %d] y=[%d, %d] z=[%d, %d] (full volume shape)\n",
            dataBounds_.minX, dataBounds_.maxX,
            dataBounds_.minY, dataBounds_.maxY,
            dataBounds_.minZ, dataBounds_.maxZ);
}

const Volume::DataBounds& Volume::dataBounds() const
{
    std::call_once(boundsOnce_, [this] {
        const_cast<Volume*>(this)->computeDataBounds();
    });
    return dataBounds_;
}

bool Volume::needsRemoteLevel5Prime() const
{
    if (!isRemote_) return false;
    if (zarrDs_.size() < 6) return false;  // need at least levels 0-5

    {
        std::lock_guard lock(remoteLevel5PrimeMutex_);
        if (remoteLevel5PrimeStarted_ || remoteLevel5PrimeDone_) return false;
    }

    // Check if level 5 is already fully cached locally
    const_cast<Volume*>(this)->ensureTieredCache();
    if (!tieredCache_) return false;

    auto levelShape = tieredCache_->levelShape(5);
    auto chunkShape = tieredCache_->chunkShape(5);
    int gridZ = (levelShape[0] + chunkShape[0] - 1) / chunkShape[0];
    int gridY = (levelShape[1] + chunkShape[1] - 1) / chunkShape[1];
    int gridX = (levelShape[2] + chunkShape[2] - 1) / chunkShape[2];

    return !tieredCache_->areAllCachedInRegion(5, 0, 0, 0,
                                                gridZ - 1, gridY - 1, gridX - 1);
}

void Volume::primeRemoteLevel5Blocking(
    const std::function<void(size_t completed, size_t total)>& progressCb)
{
    {
        std::lock_guard lock(remoteLevel5PrimeMutex_);
        if (remoteLevel5PrimeDone_) return;
        remoteLevel5PrimeStarted_ = true;
    }

    ensureTieredCache();
    if (!tieredCache_ || zarrDs_.size() < 6) {
        std::lock_guard lock(remoteLevel5PrimeMutex_);
        remoteLevel5PrimeDone_ = true;
        return;
    }

    auto levelShape = tieredCache_->levelShape(5);
    auto chunkShape = tieredCache_->chunkShape(5);
    int gridZ = (levelShape[0] + chunkShape[0] - 1) / chunkShape[0];
    int gridY = (levelShape[1] + chunkShape[1] - 1) / chunkShape[1];
    int gridX = (levelShape[2] + chunkShape[2] - 1) / chunkShape[2];
    size_t total = static_cast<size_t>(gridZ) * static_cast<size_t>(gridY) * static_cast<size_t>(gridX);
    size_t completed = 0;

    try {
        // Download chunks with bounded concurrency: prefetch a batch,
        // then wait for them before submitting the next batch.
        constexpr size_t kBatchSize = 32;
        std::vector<vc::cache::ChunkKey> allKeys;
        allKeys.reserve(total);
        for (int iz = 0; iz < gridZ; iz++)
            for (int iy = 0; iy < gridY; iy++)
                for (int ix = 0; ix < gridX; ix++)
                    allKeys.push_back(vc::cache::ChunkKey{5, iz, iy, ix});

        for (size_t i = 0; i < allKeys.size(); i += kBatchSize) {
            size_t end = std::min(i + kBatchSize, allKeys.size());
            for (size_t j = i; j < end; j++)
                tieredCache_->prefetch(allKeys[j]);
            for (size_t j = i; j < end; j++) {
                (void)tieredCache_->getBlocking(allKeys[j]);
                completed++;
                if (progressCb)
                    progressCb(completed, total);
            }
        }
        tieredCache_->flushPersistentState();
    } catch (...) {
        std::lock_guard lock(remoteLevel5PrimeMutex_);
        remoteLevel5PrimeStarted_ = false;
        throw;
    }

    std::lock_guard lock(remoteLevel5PrimeMutex_);
    remoteLevel5PrimeDone_ = true;
}

// ============================================================================
// Chunk query / prefetch
// ============================================================================

Volume::WorldBBox Volume::coordsWorldBBox(const cv::Mat_<cv::Vec3f>& coords) const
{
    WorldBBox wb;
    wb.loX = std::numeric_limits<float>::max();
    wb.loY = std::numeric_limits<float>::max();
    wb.loZ = std::numeric_limits<float>::max();
    wb.hiX = std::numeric_limits<float>::lowest();
    wb.hiY = std::numeric_limits<float>::lowest();
    wb.hiZ = std::numeric_limits<float>::lowest();

    if (coords.empty()) return wb;

    const int h = coords.rows;
    const int w = coords.cols;

#ifdef __aarch64__
    // NEON with vld3q_f32 to deinterleave xyz — processes 4 Vec3f (12 floats) at a time
    float32x4_t loX = vdupq_n_f32(std::numeric_limits<float>::max());
    float32x4_t loY = loX, loZ = loX;
    float32x4_t hiX = vdupq_n_f32(std::numeric_limits<float>::lowest());
    float32x4_t hiY = hiX, hiZ = hiX;

    auto scanRow = [&](const cv::Vec3f* row, int count) {
        const float* p = reinterpret_cast<const float*>(row);
        int i = 0;
        for (; i + 4 <= count; i += 4) {
            float32x4x3_t v = vld3q_f32(p + i * 3);
            loX = vminq_f32(loX, v.val[0]);
            loY = vminq_f32(loY, v.val[1]);
            loZ = vminq_f32(loZ, v.val[2]);
            hiX = vmaxq_f32(hiX, v.val[0]);
            hiY = vmaxq_f32(hiY, v.val[1]);
            hiZ = vmaxq_f32(hiZ, v.val[2]);
        }
        for (; i < count; i++) {
            float x = p[i*3], y = p[i*3+1], z = p[i*3+2];
            loX = vminq_f32(loX, vdupq_n_f32(x));
            loY = vminq_f32(loY, vdupq_n_f32(y));
            loZ = vminq_f32(loZ, vdupq_n_f32(z));
            hiX = vmaxq_f32(hiX, vdupq_n_f32(x));
            hiY = vmaxq_f32(hiY, vdupq_n_f32(y));
            hiZ = vmaxq_f32(hiZ, vdupq_n_f32(z));
        }
    };

    scanRow(coords.ptr<cv::Vec3f>(0), w);
    if (h > 1) scanRow(coords.ptr<cv::Vec3f>(h - 1), w);

    auto updateScalar = [&](const cv::Vec3f& v) {
        loX = vminq_f32(loX, vdupq_n_f32(v[0]));
        loY = vminq_f32(loY, vdupq_n_f32(v[1]));
        loZ = vminq_f32(loZ, vdupq_n_f32(v[2]));
        hiX = vmaxq_f32(hiX, vdupq_n_f32(v[0]));
        hiY = vmaxq_f32(hiY, vdupq_n_f32(v[1]));
        hiZ = vmaxq_f32(hiZ, vdupq_n_f32(v[2]));
    };

    for (int y = 1; y < h - 1; ++y) {
        const auto* row = coords.ptr<cv::Vec3f>(y);
        updateScalar(row[0]);
        updateScalar(row[w - 1]);
    }
    for (int y = 32; y < h - 1; y += 32) {
        const auto* row = coords.ptr<cv::Vec3f>(y);
        for (int x = 32; x < w - 1; x += 32)
            updateScalar(row[x]);
    }

    // Reduce each 4-lane accumulator to scalar
    wb.loX = vminvq_f32(loX); wb.hiX = vmaxvq_f32(hiX);
    wb.loY = vminvq_f32(loY); wb.hiY = vmaxvq_f32(hiY);
    wb.loZ = vminvq_f32(loZ); wb.hiZ = vmaxvq_f32(hiZ);
#else
    auto updateBounds = [&](const cv::Vec3f& v) {
        wb.loX = std::min(wb.loX, v[0]); wb.hiX = std::max(wb.hiX, v[0]);
        wb.loY = std::min(wb.loY, v[1]); wb.hiY = std::max(wb.hiY, v[1]);
        wb.loZ = std::min(wb.loZ, v[2]); wb.hiZ = std::max(wb.hiZ, v[2]);
    };

    const auto* topRow = coords.ptr<cv::Vec3f>(0);
    const auto* botRow = coords.ptr<cv::Vec3f>(h - 1);
    for (int x = 0; x < w; ++x) {
        updateBounds(topRow[x]);
        updateBounds(botRow[x]);
    }
    for (int y = 1; y < h - 1; ++y) {
        const auto* row = coords.ptr<cv::Vec3f>(y);
        updateBounds(row[0]);
        updateBounds(row[w - 1]);
    }
    for (int y = 32; y < h - 1; y += 32) {
        const auto* row = coords.ptr<cv::Vec3f>(y);
        for (int x = 32; x < w - 1; x += 32)
            updateBounds(row[x]);
    }
#endif

    return wb;
}

Volume::ChunkBBox Volume::worldBBoxToChunkBBox(const WorldBBox& wb, int level) const
{
    vc::VcDataset* ds = zarrDataset(level);
    if (!ds) return {0, -1, 0, -1, 0, -1};

    float scale = (level > 0) ? (1.0f / static_cast<float>(1 << level)) : 1.0f;
    auto cs = ds->defaultChunkShape();
    const auto& shape = ds->shape();
    float csX = static_cast<float>(cs[2]), csY = static_cast<float>(cs[1]), csZ = static_cast<float>(cs[0]);

    // Apply scale + interpolation margin
    float loX = wb.loX * scale - 2.0f;
    float loY = wb.loY * scale - 2.0f;
    float loZ = wb.loZ * scale - 2.0f;
    float hiX = wb.hiX * scale + 2.0f;
    float hiY = wb.hiY * scale + 2.0f;
    float hiZ = wb.hiZ * scale + 2.0f;

    ChunkBBox bb;
    bb.minIx = std::max(0, static_cast<int>(std::floor(loX / csX)));
    bb.maxIx = std::min(static_cast<int>(std::ceil(hiX / csX)),
                        static_cast<int>((shape[2] - 1) / cs[2]));
    bb.minIy = std::max(0, static_cast<int>(std::floor(loY / csY)));
    bb.maxIy = std::min(static_cast<int>(std::ceil(hiY / csY)),
                        static_cast<int>((shape[1] - 1) / cs[1]));
    bb.minIz = std::max(0, static_cast<int>(std::floor(loZ / csZ)));
    bb.maxIz = std::min(static_cast<int>(std::ceil(hiZ / csZ)),
                        static_cast<int>((shape[0] - 1) / cs[0]));
    return bb;
}

Volume::ChunkBBox Volume::coordsToChunkBBox(
    const cv::Mat_<cv::Vec3f>& coords, int level) const
{
    return worldBBoxToChunkBBox(coordsWorldBBox(coords), level);
}

bool Volume::allChunksCachedFast(const WorldBBox& wb, int level) const
{
    ensureTieredCache();
    if (!tieredCache_) return false;

    auto bb = worldBBoxToChunkBBox(wb, level);
    if (bb.minIx > bb.maxIx || bb.minIy > bb.maxIy || bb.minIz > bb.maxIz) return false;

    return tieredCache_->areAllCachedInRegion(
        level, bb.minIz, bb.minIy, bb.minIx,
        bb.maxIz, bb.maxIy, bb.maxIx);
}

void Volume::prefetchChunks(const cv::Mat_<cv::Vec3f>& coords, int level)
{
    ensureTieredCache();
    if (!tieredCache_) return;

    auto bb = coordsToChunkBBox(coords, level);
    if (bb.minIx > bb.maxIx || bb.minIy > bb.maxIy || bb.minIz > bb.maxIz) return;  // invalid bbox

    tieredCache_->prefetchRegion(level,
        bb.minIz, bb.minIy, bb.minIx,
        bb.maxIz, bb.maxIy, bb.maxIx);
}

void Volume::prefetchLevels(int fromLevel, int toLevel)
{
    ensureTieredCache();
    if (!tieredCache_) return;

    int maxLevel = tieredCache_->numLevels() - 1;
    fromLevel = std::clamp(fromLevel, 0, maxLevel);
    toLevel = std::clamp(toLevel, 0, maxLevel);

    // Spawn a detached background thread — never blocks the GUI
    std::thread([cache = tieredCache_.get(), fromLevel, toLevel, &stop = prefetchStop_]() {
        stop.store(false, std::memory_order_relaxed);

        // Load the coarsest level into dedicated flat storage, then scan for
        // all-zero chunks and propagate to finer levels.
        // This eliminates network requests for chunks in masked/padded regions.
        cache->loadCoarseLevel(toLevel);
        cache->propagateZeroChunks(toLevel);

        for (int lvl = toLevel - 1; lvl >= fromLevel && !stop.load(std::memory_order_relaxed); lvl--) {
            auto ls = cache->levelShape(lvl);
            auto cs = cache->chunkShape(lvl);
            int gridZ = (ls[0] + cs[0] - 1) / cs[0];
            int gridY = (ls[1] + cs[1] - 1) / cs[1];
            int gridX = (ls[2] + cs[2] - 1) / cs[2];
            int total = gridZ * gridY * gridX;

            std::fprintf(stderr, "[Volume] Prefetching level %d (%d chunks)...\n",
                         lvl, total);

            cache->prefetchLevel(lvl, [lvl](int fetched, int t) {
                if (fetched % 5000 < 1000)
                    std::fprintf(stderr, "[Volume] Level %d prefetch: %d/%d\n",
                                 lvl, fetched, t);
            });
            std::fprintf(stderr, "[Volume] Level %d prefetch: %d/%d done\n",
                         lvl, total, total);
        }
        std::fprintf(stderr, "[Volume] Level prefetch complete (levels %d-%d)\n",
                     fromLevel, toLevel);
    }).detach();
}

void Volume::cancelPendingPrefetch()
{
    // Stop the prefetch thread first
    prefetchStop_.store(true, std::memory_order_relaxed);
    if (tieredCache_) {
        tieredCache_->cancelPendingPrefetch();
    }
}

void Volume::prefetchWorldBBox(const cv::Vec3f& lo, const cv::Vec3f& hi, int level)
{
    ensureTieredCache();
    if (!tieredCache_) return;

    vc::VcDataset* ds = zarrDataset(level);
    if (!ds) return;

    float scale = (level > 0) ? (1.0f / static_cast<float>(1 << level)) : 1.0f;
    auto cs = ds->defaultChunkShape();  // {cz, cy, cx}
    const auto& shape = ds->shape();    // {z, y, x}
    float csX = static_cast<float>(cs[2]), csY = static_cast<float>(cs[1]), csZ = static_cast<float>(cs[0]);

    // Apply margin to float coords, then floor/ceil to chunk indices
    float sLoX = lo[0] * scale - 1.0f;
    float sHiX = hi[0] * scale + 1.0f;
    float sLoY = lo[1] * scale - 1.0f;
    float sHiY = hi[1] * scale + 1.0f;
    float sLoZ = lo[2] * scale - 1.0f;
    float sHiZ = hi[2] * scale + 1.0f;

    int minIx = std::max(0, static_cast<int>(std::floor(sLoX / csX)));
    int maxIx = std::min(static_cast<int>((shape[2] - 1) / cs[2]),
                         static_cast<int>(std::ceil(sHiX / csX)));
    int minIy = std::max(0, static_cast<int>(std::floor(sLoY / csY)));
    int maxIy = std::min(static_cast<int>((shape[1] - 1) / cs[1]),
                         static_cast<int>(std::ceil(sHiY / csY)));
    int minIz = std::max(0, static_cast<int>(std::floor(sLoZ / csZ)));
    int maxIz = std::min(static_cast<int>((shape[0] - 1) / cs[0]),
                         static_cast<int>(std::ceil(sHiZ / csZ)));

    if (minIx > maxIx || minIy > maxIy || minIz > maxIz) return;

    tieredCache_->prefetchRegion(level, minIz, minIy, minIx, maxIz, maxIy, maxIx);
}
