#include "vc/core/types/Volume.hpp"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <limits>
#include <mutex>
#include <optional>
#include <unordered_map>

#ifdef __aarch64__
#include <arm_neon.h>
#endif

#include <opencv2/imgcodecs.hpp>
#include "vc/core/util/LoadJson.hpp"
#include "vc/core/util/Slicing.hpp"
#include "vc/core/cache/BlockPipeline.hpp"
#include "vc/core/cache/VolumeSource.hpp"
#include "vc/core/cache/VcDecompressor.hpp"
#include <utils/zarr.hpp>
#include "vc/core/cache/HttpMetadataFetcher.hpp"
#include "vc/core/util/RemoteUrl.hpp"
#include "vc/core/util/NetworkFilesystem.hpp"
#include "vc/core/util/PostProcess.hpp"
#include "vc/core/types/VcDataset.hpp"

static const std::filesystem::path METADATA_FILE = "meta.json";
static const std::filesystem::path METADATA_FILE_ALT = "metadata.json";

Volume::Volume(std::filesystem::path path) : path_(std::move(path))
{
    loadMetadata();

    _width = metadata_["width"].get_int();
    _height = metadata_["height"].get_int();
    _slices = metadata_["slices"].get_int();

    zarrOpen();
    mountInfo_ = vc::detectNetworkMount(path_);
}

Volume::~Volume() noexcept = default;

void Volume::loadMetadata()
{
    metadataAutoGenerated_ = false;

    auto metaPath = path_ / METADATA_FILE;
    if (std::filesystem::exists(metaPath)) {
        metadata_ = vc::json::load_json_file(metaPath);
    } else if (std::filesystem::exists(path_ / METADATA_FILE_ALT)) {
        auto altPath = path_ / METADATA_FILE_ALT;
        auto full = vc::json::load_json_file(altPath);
        if (!full.contains("scan")) {
            throw std::runtime_error(
                "metadata.json missing 'scan' key: " + altPath.string());
        }
        metadata_ = full["scan"];
        if (!metadata_.contains("format")) {
            metadata_["format"] = "zarr";
        }
        metaPath = altPath;
    } else {
        const auto baseName = path_.filename().string();
        metadata_["uuid"] = baseName;
        metadata_["name"] = baseName;
        metadata_["type"] = "vol";
        metadata_["format"] = "zarr";
        metadata_["width"] = 0;
        metadata_["height"] = 0;
        metadata_["slices"] = 0;
        metadata_["voxelsize"] = double{};
        metadata_["min"] = double{};
        metadata_["max"] = double{};
        metadataAutoGenerated_ = true;
        return;
    }
    vc::json::require_type(metadata_, "type", "vol", metaPath.string());
    vc::json::require_fields(metadata_, {"uuid", "width", "height", "slices"}, metaPath.string());
}

std::string Volume::id() const
{
    return metadata_["uuid"].get_string();
}

std::string Volume::name() const
{
    return metadata_["name"].get_string();
}

bool Volume::checkDir(const std::filesystem::path& path)
{
    return std::filesystem::is_directory(path) &&
           (std::filesystem::exists(path / METADATA_FILE) ||
            std::filesystem::exists(path / METADATA_FILE_ALT) ||
            std::filesystem::exists(path / ".zgroup") ||
            std::filesystem::exists(path / ".zattrs"));
}

static int ceilDivPow2(int v, int level)
{
    const int64_t denom = int64_t{1} << level;
    return static_cast<int>((static_cast<int64_t>(v) + denom - 1) / denom);
}

void Volume::zarrOpen()
{
    if (!metadata_.contains("format") || metadata_["format"].get_string() != "zarr")
        return;

    {
        auto compactDs = vc::openZarrLevels(path_);

        // Reindex so zarrDs_[i] corresponds to actual scale level i.
        // openZarrLevels() returns a compact vector; directory names give the
        // true level number. Power-of-2 scaling is assumed but not every level
        // needs to be present (e.g. only levels 1,2,3 or 0,2).
        int maxLevel = 0;
        for (auto& ds : compactDs) {
            try {
                int lvl = std::stoi(ds->path().filename().string());
                maxLevel = std::max(maxLevel, lvl);
            } catch (...) {}
        }
        zarrDs_.resize(maxLevel + 1);
        for (auto& ds : compactDs) {
            try {
                int lvl = std::stoi(ds->path().filename().string());
                zarrDs_[lvl] = std::move(ds);
            } catch (...) {}
        }
    }

    for (size_t i = 0; i < zarrDs_.size(); i++) {
        if (!zarrDs_[i]) continue;  // missing level
        auto dtype = zarrDs_[i]->getDtype();
        if (dtype != vc::VcDtype::uint8 && dtype != vc::VcDtype::uint16)
            throw std::runtime_error("only uint8 & uint16 is currently supported for zarr datasets, incompatible type found in " + path_.string());
    }

    if (metadataAutoGenerated_) {

        bool hasReference = false;
        int baseSlices = 0;
        int baseHeight = 0;
        int baseWidth = 0;

        for (size_t level = 0; level < zarrDs_.size(); ++level) {
            const auto& ds = zarrDs_[level];
            if (!ds) {
                continue;
            }

            const auto& shape = ds->shape();
            const int levelInt = static_cast<int>(level);

            if (!hasReference) {
                const size_t scale = size_t{1} << levelInt;
                baseSlices = static_cast<int>(shape[0] * scale);
                baseHeight = static_cast<int>(shape[1] * scale);
                baseWidth = static_cast<int>(shape[2] * scale);
                hasReference = true;
            }

            const int expectedSlices = ceilDivPow2(baseSlices, levelInt);
            const int expectedHeight = ceilDivPow2(baseHeight, levelInt);
            const int expectedWidth = ceilDivPow2(baseWidth, levelInt);

            constexpr int kMaxPerLevelPad = 128;
            auto padOK = [](long long actual, long long expected) {
                return actual >= expected && actual - expected < kMaxPerLevelPad;
            };
            if (!padOK(shape[0], expectedSlices) ||
                !padOK(shape[1], expectedHeight) ||
                !padOK(shape[2], expectedWidth)) {
                throw std::runtime_error(
                    "zarr level " + std::to_string(levelInt) + " shape [z,y,x]=("
                    + std::to_string(shape[0]) + ", " + std::to_string(shape[1]) + ", " + std::to_string(shape[2])
                    + ") does not match synthesized dimensions from first found scale (slices=" + std::to_string(baseSlices)
                    + ", height=" + std::to_string(baseHeight) + ", width=" + std::to_string(baseWidth)
                    + ") in " + path_.string());
            }
        }

        _slices = baseSlices;
        _height = baseHeight;
        _width = baseWidth;
        metadata_["slices"] = _slices;
        metadata_["height"] = _height;
        metadata_["width"] = _width;
    }

    // Verify each existing level shape against meta.json dimensions and level downscale.
    // zarr shape is [z, y, x] = [slices, height, width]
    if (!skipShapeCheck) {
        bool hasAnyPhysicalScale = false;
        for (size_t level = 0; level < zarrDs_.size(); ++level) {
            const auto& ds = zarrDs_[level];
            if (!ds) {
                continue;
            }
            hasAnyPhysicalScale = true;

            const auto& shape = ds->shape();
            const int expectedSlices = ceilDivPow2(_slices, static_cast<int>(level));
            const int expectedHeight = ceilDivPow2(_height, static_cast<int>(level));
            const int expectedWidth = ceilDivPow2(_width, static_cast<int>(level));

            constexpr int kMaxPerLevelPad = 128;
            auto padOK = [](long long actual, long long expected) {
                return actual >= expected && actual - expected < kMaxPerLevelPad;
            };
            if (!padOK(shape[0], expectedSlices) ||
                !padOK(shape[1], expectedHeight) ||
                !padOK(shape[2], expectedWidth)) {
                throw std::runtime_error(
                    "zarr level " + std::to_string(level) + " shape [z,y,x]=("
                    + std::to_string(shape[0]) + ", " + std::to_string(shape[1]) + ", " + std::to_string(shape[2])
                    + ") does not match expected downscaled meta.json dimensions (slices=" + std::to_string(expectedSlices)
                    + ", height=" + std::to_string(expectedHeight) + ", width=" + std::to_string(expectedWidth)
                    + ") in " + path_.string());
            }
        }
        if (!hasAnyPhysicalScale)
            throw std::runtime_error("no physical zarr dataset directories found in " + path_.string());
    }
}

std::shared_ptr<Volume> Volume::New(std::filesystem::path path)
{
    return std::make_shared<Volume>(std::move(path));
}

std::shared_ptr<Volume> Volume::NewFromUrl(
    const std::string& url,
    const std::filesystem::path& cacheRoot,
    const vc::cache::HttpAuth& authIn)
{
    namespace fs = std::filesystem;

    // Resolve s3:// URLs to https:// and detect AWS credentials
    auto resolved = vc::resolveRemoteUrl(url);
    vc::cache::HttpAuth auth = authIn;
    if (resolved.useAwsSigv4 && auth.empty()) {
        auth = vc::cache::loadAwsCredentials();
        if (auth.region.empty())
            auth.region = resolved.awsRegion;
        // SigV4 is implicitly enabled when access_key is non-empty.
        // If credentials are missing, clear them so the request proceeds
        // unsigned (anonymous access for public buckets).
        if (auth.access_key.empty() || auth.secret_key.empty())
            auth = {};  // anonymous — no SigV4
    } else if (resolved.useAwsSigv4 && auth.region.empty()) {
        auth.region = resolved.awsRegion;
    }

    // Determine cache root
    fs::path root = cacheRoot;
    if (root.empty()) {
        root = fs::path(std::getenv("HOME") ? std::getenv("HOME") : "/tmp") / ".VC3D" / "remote_cache";
    }

    // Fetch remote metadata (downloads .zarray files, synthesizes meta.json)
    auto info = vc::cache::fetchRemoteZarrMetadata(resolved.httpsUrl, root, auth);

    // Temporarily skip shape validation (staging dir has no chunk data)
    struct SkipShapeGuard {
        bool prev;
        SkipShapeGuard() : prev(skipShapeCheck) { skipShapeCheck = true; }
        ~SkipShapeGuard() { skipShapeCheck = prev; }
    };
    SkipShapeGuard guard;

    auto vol = std::make_shared<Volume>(info.stagingDir);

    vol->isRemote_ = true;
    vol->remoteUrl_ = info.url;
    vol->remoteDelimiter_ = info.delimiter;
    vol->remoteAuth_ = auth;
    vol->remoteShardConfig_ = info.shardConfig;

    return vol;
}

int Volume::sliceWidth() const noexcept { return _width; }
int Volume::sliceHeight() const noexcept { return _height; }
int Volume::numSlices() const noexcept { return _slices; }
std::array<int, 3> Volume::shape() const noexcept { return {_width, _height, _slices}; }
double Volume::voxelSize() const
{
    return metadata_["voxelsize"].get_double();
}

vc::VcDataset *Volume::zarrDataset(int level) const {
    if (level < 0 || zarrDs_.empty())
        return nullptr;

    if (static_cast<size_t>(level) >= zarrDs_.size())
        return nullptr;

    return zarrDs_[static_cast<size_t>(level)].get();
}

size_t Volume::numScales() const noexcept {
    return zarrDs_.size();
}

std::unique_ptr<vc::cache::BlockPipeline> Volume::createTieredCache() const
{
    if (zarrDs_.empty()) return nullptr;
    std::vector<std::unique_ptr<utils::ZarrArray>> diskLevels;

    // Build level metadata from our zarr datasets. The vector is padded so
    // index = actual scale level; missing levels have default (zero) shapes.
    std::vector<vc::cache::FileSystemSource::LevelMeta> levels(zarrDs_.size());
    std::string delimiter;
    for (size_t i = 0; i < zarrDs_.size(); ++i) {
        if (!zarrDs_[i]) continue;  // missing level — leave default {0,0,0}
        auto& ds = zarrDs_[i];
        auto& lm = levels[i];
        const auto& shape = ds->shape();
        const auto& chunks = ds->defaultChunkShape();
        lm.dirName = ds->path().filename().string();
        lm.shape = {
            static_cast<int>(shape[0]),
            static_cast<int>(shape[1]),
            static_cast<int>(shape[2])};
        lm.chunkShape = {
            static_cast<int>(chunks[0]),
            static_cast<int>(chunks[1]),
            static_cast<int>(chunks[2])};
        if (delimiter.empty())
            delimiter = ds->delimiter();
    }

    // Create chunk source: HTTP for remote volumes, filesystem for local
    std::unique_ptr<vc::cache::VolumeSource> source;

    if (isRemote_) {
        auto httpSource = std::make_unique<vc::cache::HttpSource>(
            remoteUrl_, remoteDelimiter_, std::move(levels), remoteAuth_);
        if (remoteShardConfig_.enabled) {
            httpSource->setShardConfig(remoteShardConfig_);
        }
        source = std::move(httpSource);

        // v3 sharded disk cache: path_/0/, path_/1/, ...
        // c3d canonical layout: 4096³ shards with 256³ inner C3DC chunks.
        // Open per-level zarr.json if it exists, create if not.
        {
            const int nLevels = source->numLevels();
            diskLevels.resize(nLevels);

            auto pad256 = [](int v) -> size_t {
                return static_cast<size_t>((v + 255) / 256 * 256);
            };

            auto createLevel = [&](const std::filesystem::path& lvlPath, int lvl) {
                auto shape = source->levelShape(lvl);
                utils::ZarrMetadata meta;
                meta.version = utils::ZarrVersion::v3;
                meta.node_type = "array";
                meta.shape = {pad256(shape[0]), pad256(shape[1]), pad256(shape[2])};
                meta.chunks = {4096, 4096, 4096};
                meta.dtype = utils::ZarrDtype::uint8;
                meta.fill_value = 0;
                meta.chunk_key_encoding = "default";
                utils::ShardConfig sc;
                sc.sub_chunks = {256, 256, 256};
                utils::ZarrCodecConfig cc;
                cc.name = "c3d";
                sc.sub_codecs.push_back(cc);
                meta.shard_config = std::move(sc);
                return std::make_unique<utils::ZarrArray>(
                    utils::ZarrArray::create(lvlPath, std::move(meta)));
            };

            for (int lvl = 0; lvl < nLevels; lvl++) {
                auto lvlPath = path_ / std::to_string(lvl);
                if (std::filesystem::exists(lvlPath / "zarr.json")) {
                    auto opened = std::make_unique<utils::ZarrArray>(
                        utils::ZarrArray::open(lvlPath));
                    if (utils::is_canonical_c3d(opened->metadata())) {
                        diskLevels[lvl] = std::move(opened);
                    } else {
                        // Legacy h265 (or any non-c3d) level from before the
                        // codec switch. The decoder in BlockPipeline now only
                        // accepts C3DC, so leaving stale entries in place
                        // would silently mark chunks as "on disk" without
                        // ever producing data. Nuke the level dir and create
                        // a fresh c3d one; the remote source will repopulate.
                        opened.reset();
                        fprintf(stderr,
                            "[Volume] level %d cache at %s is non-c3d — "
                            "wiping and recreating as c3d\n",
                            lvl, lvlPath.c_str());
                        std::error_code ec;
                        std::filesystem::remove_all(lvlPath, ec);
                        if (ec) {
                            throw std::runtime_error(
                                "failed to remove stale non-c3d cache at "
                                + lvlPath.string() + ": " + ec.message());
                        }
                        diskLevels[lvl] = createLevel(lvlPath, lvl);
                    }
                } else {
                    diskLevels[lvl] = createLevel(lvlPath, lvl);
                }
            }
            fprintf(stderr,
                "[Volume] Cold cache: %d levels at %s (codec: c3d)\n",
                nLevels, path_.c_str());
        }
    } else {
        source = std::make_unique<vc::cache::FileSystemSource>(
            path_, delimiter, std::move(levels));

        // Network mount disk caching disabled — needs per-level conversion
        if (mountInfo_.type == vc::FilesystemType::NetworkMount) {
            fprintf(stderr, "[Volume] Network mount detected — disk cache not yet per-level, skipping\n");
        }
    }

    // Build dataset pointers for the decompressor
    std::vector<vc::VcDataset*> dsPtrs;
    dsPtrs.reserve(zarrDs_.size());
    for (auto& ds : zarrDs_) {
        dsPtrs.push_back(ds.get());
    }
    auto decompress = vc::cache::makeVcDecompressor(dsPtrs);

    vc::cache::BlockPipeline::Config config;
    config.volumeId = id();
    config.bytes = cacheBudgetHot_;
    config.c3dEncodeParams = encodeParams_;

    // Canonical-passthrough detection. Remote sources matching our local
    // c3d disk cache (4096³ shards with 256³ inner C3DC chunks) get
    // whole-shard byte-passthrough — one HTTP request + one disk write
    // per source shard instead of decoding and re-encoding every inner
    // chunk. We probe level 0 zarr.json directly because the
    // remoteShardConfig from NewFromUrl isn't always populated.
    if (isRemote_) {
        try {
            auto resolved = vc::resolveRemoteUrl(remoteUrl_);
            const std::string base = resolved.httpsUrl
                + (resolved.httpsUrl.back() == '/' ? "" : "/");
            auto json = vc::cache::httpGetString(base + "0/zarr.json", remoteAuth_);
            if (!json.empty()) {
                auto meta = utils::detail::parse_zarr_json(json);
                if (utils::is_canonical_c3d(meta)
                    && meta.chunks.size() >= 3
                    && meta.chunks[0] == 4096
                    && meta.chunks[1] == 4096
                    && meta.chunks[2] == 4096) {
                    config.canonicalSourceShard = {4096, 4096, 4096};
                    fprintf(stderr,
                        "[Volume] canonical-passthrough enabled "
                        "(c3d source shards 4096^3 match local)\n");
                }
            }
        } catch (const std::exception& e) {
            fprintf(stderr,
                "[Volume] canonical-passthrough detection failed: %s\n",
                e.what());
        }
    }
    if (isRemote_ || mountInfo_.type == vc::FilesystemType::NetworkMount) {
        if (ioThreads_ > 0) {
            config.ioThreads = ioThreads_;
        } else if (mountInfo_.parallelCount > 0) {
            config.ioThreads = mountInfo_.parallelCount;
        } else {
            config.ioThreads = 8;  // HTTP/2 multiplexing: fewer connections, many streams each
        }
        fprintf(stderr, "[Volume] IO threads: %d\n", config.ioThreads);
    }

    // Use the shared BlockCache if one was provided; otherwise create a
    // local one (CLI tools, tests, etc.).
    static thread_local std::unique_ptr<vc::cache::BlockCache> localBlockCache;
    vc::cache::BlockCache* bc = sharedBlockCache_;
    if (!bc) {
        vc::cache::BlockCache::Config bcfg;
        bcfg.bytes = cacheBudgetHot_;
        for (auto& f : bcfg.levelFloor) f = 4096;
        localBlockCache = std::make_unique<vc::cache::BlockCache>(bcfg);
        bc = localBlockCache.get();
    }

    auto pipeline = std::make_unique<vc::cache::BlockPipeline>(
        std::move(config),
        *bc,
        std::move(source),
        std::move(decompress),
        std::move(diskLevels));
    return pipeline;
}

// ============================================================================
// Cache management
// ============================================================================

void Volume::ensureTieredCache() const
{
    std::lock_guard<std::mutex> lock(cacheMutex_);
    if (!tieredCache_) {
        auto* self = const_cast<Volume*>(this);
        tieredCache_ = self->createTieredCache();
    }
}

vc::cache::BlockPipeline* Volume::tieredCache()
{
    ensureTieredCache();
    return tieredCache_.get();
}

void Volume::resetTieredCache()
{
    std::lock_guard<std::mutex> lock(cacheMutex_);
    tieredCache_.reset();
}

void Volume::setCacheBudget(size_t hotBytes)
{
    cacheBudgetHot_ = hotBytes;
}

void Volume::setBlockCache(vc::cache::BlockCache* bc)
{
    sharedBlockCache_ = bc;
}

void Volume::setIOThreads(int count)
{
    ioThreads_ = count;
}

void Volume::setEncodeParams(const utils::C3dCodecParams& params)
{
    if (tieredCache_) {
        fprintf(stderr, "[Volume] WARNING: setEncodeParams() called after cache "
                        "already created — ignoring\n");
        return;
    }
    encodeParams_ = params;
}

// ============================================================================
// Sampling API
// ============================================================================

// Helper: apply optional post-processing from SampleParams in-place.
static void applyOptionalPostProcess(cv::Mat_<uint8_t>& img,
                                     const vc::SampleParams& params)
{
    if (!params.postProcess) return;
    vc::applyPostProcess(img, *params.postProcess);
}

// Helper: scale level-0 coords to pyramid level coords.
static const cv::Mat_<cv::Vec3f>& scaleCoords(const cv::Mat_<cv::Vec3f>& coords, int level)
{
    if (level <= 0) return coords;
    // Thread-local buffer avoids per-tile allocation for the scaled copy
    thread_local cv::Mat_<cv::Vec3f> scaled;
    float scale = 1.0f / static_cast<float>(1 << level);
    if (scaled.rows != coords.rows || scaled.cols != coords.cols) {
        scaled.create(coords.size());
    }
    const int total = coords.rows * coords.cols;
    const auto* src = coords.ptr<cv::Vec3f>();
    auto* dst = scaled.ptr<cv::Vec3f>();
    for (int i = 0; i < total; ++i) {
        dst[i] = src[i] * scale;
    }
    return scaled;
}

void Volume::sample(cv::Mat_<uint8_t>& out,
                    const cv::Mat_<cv::Vec3f>& coords,
                    const vc::SampleParams& params)
{
    const auto& scaled = scaleCoords(coords, params.level);
    readInterpolated3D(out, tieredCache(), params.level, scaled, params.method);
    applyOptionalPostProcess(out, params);
}

void Volume::sample(cv::Mat_<uint16_t>& out,
                    const cv::Mat_<cv::Vec3f>& coords,
                    const vc::SampleParams& params)
{
    const auto& scaled = scaleCoords(coords, params.level);
    readInterpolated3D(out, tieredCache(), params.level, scaled, params.method);
}

int Volume::sampleBestEffort(cv::Mat_<uint8_t>& out,
                              const cv::Mat_<cv::Vec3f>& coords,
                              const vc::SampleParams& params)
{
    const int nScales = static_cast<int>(numScales());
    const int level = std::clamp(params.level, 0, std::max(0, nScales - 1));
    const auto& scaled = scaleCoords(coords, level);
    readInterpolated3D(out, tieredCache(), level, scaled, params.method);
    if (!out.empty())
        applyOptionalPostProcess(out, params);
    return level;
}

void Volume::sampleComposite(cv::Mat_<uint8_t>& out,
                              const cv::Mat_<cv::Vec3f>& coords,
                              const cv::Mat_<cv::Vec3f>& normals,
                              const vc::SampleParams& params)
{
    float scale = (params.level > 0) ? (1.0f / static_cast<float>(1 << params.level)) : 1.0f;
    const auto& scaled = scaleCoords(coords, params.level);
    readCompositeFast(out, tieredCache(), params.level, scaled, normals, scale,
                      params.zStart, params.zEnd,
                      params.composite.value_or(CompositeParams{}),
                      params.method);
    applyOptionalPostProcess(out, params);
}

int Volume::sampleCompositeBestEffort(cv::Mat_<uint8_t>& out,
                                       const cv::Mat_<cv::Vec3f>& coords,
                                       const cv::Mat_<cv::Vec3f>& normals,
                                       const vc::SampleParams& params)
{
    const int nScales = static_cast<int>(numScales());
    const int level = std::clamp(params.level, 0, std::max(0, nScales - 1));
    vc::SampleParams lvlParams = params;
    lvlParams.level = level;
    sampleComposite(out, coords, normals, lvlParams);
    return level;
}


int Volume::samplePlaneBestEffort(cv::Mat_<uint8_t>& out,
                                   const cv::Vec3f& origin,
                                   const cv::Vec3f& vx_step,
                                   const cv::Vec3f& vy_step,
                                   int width, int height,
                                   const vc::SampleParams& params)
{
    const int nScales = static_cast<int>(numScales());
    const int level = params.level;

    int lvl = std::clamp(level, 0, std::max(0, nScales - 1));
    float scale = (lvl > 0) ? (1.0f / static_cast<float>(1 << lvl)) : 1.0f;
    samplePlane(out, tieredCache(), lvl,
                origin * scale, vx_step * scale, vy_step * scale,
                width, height, params.method);
    if (!out.empty())
        applyOptionalPostProcess(out, params);
    return lvl;
}

int Volume::samplePlaneCompositeBestEffortARGB32(
    uint32_t* outBuf, int outStride,
    const cv::Vec3f& origin, const cv::Vec3f& vx_step, const cv::Vec3f& vy_step,
    const cv::Vec3f& normal, float zStep, int zStart, int numLayers,
    int width, int height,
    const std::string& compositeMethod,
    const uint32_t lut[256])
{
    samplePlaneCompositeARGB32(outBuf, outStride, tieredCache(), 0,
        origin, vx_step, vy_step,
        normal, zStep, zStart, numLayers,
        width, height, compositeMethod, lut);
    return 0;
}

// ============================================================================
// Composite-aware chunk helpers
// ============================================================================


// ============================================================================
// Data bounds
// ============================================================================

void Volume::computeDataBounds()
{
    // Set bounds to the full volume shape — no scanning needed.
    dataBounds_.minX = 0;
    dataBounds_.maxX = _width - 1;
    dataBounds_.minY = 0;
    dataBounds_.maxY = _height - 1;
    dataBounds_.minZ = 0;
    dataBounds_.maxZ = _slices - 1;
    dataBounds_.valid = true;

    // Push to cache so ChunkSampler can skip chunks outside bounds
    ensureTieredCache();
    if (tieredCache_) {
        tieredCache_->setDataBounds(
            dataBounds_.minX, dataBounds_.maxX,
            dataBounds_.minY, dataBounds_.maxY,
            dataBounds_.minZ, dataBounds_.maxZ);
    }

    fprintf(stderr, "[Volume] dataBounds: x=[%d, %d] y=[%d, %d] z=[%d, %d] (full volume shape)\n",
            dataBounds_.minX, dataBounds_.maxX,
            dataBounds_.minY, dataBounds_.maxY,
            dataBounds_.minZ, dataBounds_.maxZ);
}

const Volume::DataBounds& Volume::dataBounds() const
{
    std::call_once(boundsOnce_, [this] {
        const_cast<Volume*>(this)->computeDataBounds();
    });
    return dataBounds_;
}


