#include "vc/core/types/Volume.hpp"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <limits>
#include <mutex>
#include <optional>
#include <thread>

#ifdef __aarch64__
#include <arm_neon.h>
#endif

#include <opencv2/imgcodecs.hpp>
#include "vc/core/util/LoadJson.hpp"
#include "vc/core/util/Slicing.hpp"
#include "vc/core/cache/BlockPipeline.hpp"
#include "vc/core/cache/VolumeSource.hpp"
#include "vc/core/cache/VcDecompressor.hpp"
#include <utils/zarr.hpp>
#include "vc/core/cache/HttpMetadataFetcher.hpp"
#include "vc/core/util/RemoteUrl.hpp"
#include "vc/core/util/NetworkFilesystem.hpp"
#include "vc/core/util/PostProcess.hpp"
#include "vc/core/types/VcDataset.hpp"

static const std::filesystem::path METADATA_FILE = "meta.json";
static const std::filesystem::path METADATA_FILE_ALT = "metadata.json";

Volume::Volume(std::filesystem::path path) : path_(std::move(path))
{
    loadMetadata();

    _width = metadata_["width"].get_int();
    _height = metadata_["height"].get_int();
    _slices = metadata_["slices"].get_int();

    zarrOpen();
    mountInfo_ = vc::detectNetworkMount(path_);
}

Volume::~Volume() noexcept = default;

void Volume::loadMetadata()
{
    metadataAutoGenerated_ = false;

    auto metaPath = path_ / METADATA_FILE;
    if (std::filesystem::exists(metaPath)) {
        metadata_ = vc::json::load_json_file(metaPath);
    } else if (std::filesystem::exists(path_ / METADATA_FILE_ALT)) {
        auto altPath = path_ / METADATA_FILE_ALT;
        auto full = vc::json::load_json_file(altPath);
        if (!full.contains("scan")) {
            throw std::runtime_error(
                "metadata.json missing 'scan' key: " + altPath.string());
        }
        metadata_ = full["scan"];
        if (!metadata_.contains("format")) {
            metadata_["format"] = "zarr";
        }
        metaPath = altPath;
    } else {
        const auto baseName = path_.filename().string();
        metadata_["uuid"] = baseName;
        metadata_["name"] = baseName;
        metadata_["type"] = "vol";
        metadata_["format"] = "zarr";
        metadata_["width"] = 0;
        metadata_["height"] = 0;
        metadata_["slices"] = 0;
        metadata_["voxelsize"] = double{};
        metadata_["min"] = double{};
        metadata_["max"] = double{};
        metadataAutoGenerated_ = true;
        return;
    }
    vc::json::require_type(metadata_, "type", "vol", metaPath.string());
    vc::json::require_fields(metadata_, {"uuid", "width", "height", "slices"}, metaPath.string());
}

std::string Volume::id() const
{
    return metadata_["uuid"].get_string();
}

std::string Volume::name() const
{
    return metadata_["name"].get_string();
}

bool Volume::checkDir(const std::filesystem::path& path)
{
    return std::filesystem::is_directory(path) &&
           (std::filesystem::exists(path / METADATA_FILE) ||
            std::filesystem::exists(path / METADATA_FILE_ALT) ||
            std::filesystem::exists(path / ".zgroup") ||
            std::filesystem::exists(path / ".zattrs"));
}

static int ceilDivPow2(int v, int level)
{
    const int64_t denom = int64_t{1} << level;
    return static_cast<int>((static_cast<int64_t>(v) + denom - 1) / denom);
}

void Volume::zarrOpen()
{
    if (!metadata_.contains("format") || metadata_["format"].get_string() != "zarr")
        return;

    zarrDs_ = vc::openZarrLevels(path_);

    for (size_t i = 0; i < zarrDs_.size(); i++) {
        auto dtype = zarrDs_[i]->getDtype();
        if (dtype != vc::VcDtype::uint8 && dtype != vc::VcDtype::uint16)
            throw std::runtime_error("only uint8 & uint16 is currently supported for zarr datasets, incompatible type found in " + path_.string());
    }

    if (metadataAutoGenerated_) {

        bool hasReference = false;
        int baseSlices = 0;
        int baseHeight = 0;
        int baseWidth = 0;

        for (size_t level = 0; level < zarrDs_.size(); ++level) {
            const auto& ds = zarrDs_[level];
            if (!ds) {
                continue;
            }

            const auto& shape = ds->shape();
            const int levelInt = static_cast<int>(level);

            if (!hasReference) {
                const size_t scale = size_t{1} << levelInt;
                baseSlices = static_cast<int>(shape[0] * scale);
                baseHeight = static_cast<int>(shape[1] * scale);
                baseWidth = static_cast<int>(shape[2] * scale);
                hasReference = true;
            }

            const int expectedSlices = ceilDivPow2(baseSlices, levelInt);
            const int expectedHeight = ceilDivPow2(baseHeight, levelInt);
            const int expectedWidth = ceilDivPow2(baseWidth, levelInt);

            // Canonical format pads each level's shape to a multiple of the
            // inner chunk size (128³), independently per level. Accept any
            // zarr_shape that exceeds expected by less than one chunk —
            // anything larger indicates real corruption.
            constexpr int kMaxPerLevelPad = 128;
            auto padOK = [](long long actual, long long expected) {
                return actual >= expected && actual - expected < kMaxPerLevelPad;
            };
            if (!padOK(shape[0], expectedSlices) ||
                !padOK(shape[1], expectedHeight) ||
                !padOK(shape[2], expectedWidth)) {
                throw std::runtime_error(
                    "zarr level " + std::to_string(levelInt) + " shape [z,y,x]=("
                    + std::to_string(shape[0]) + ", " + std::to_string(shape[1]) + ", " + std::to_string(shape[2])
                    + ") does not match synthesized dimensions from first found scale (slices=" + std::to_string(baseSlices)
                    + ", height=" + std::to_string(baseHeight) + ", width=" + std::to_string(baseWidth)
                    + ") in " + path_.string());
            }
        }

        if (!hasReference) {
            throw std::runtime_error("no physical zarr dataset directories found in " + path_.string());
        }

        _slices = baseSlices;
        _height = baseHeight;
        _width = baseWidth;
        metadata_["slices"] = _slices;
        metadata_["height"] = _height;
        metadata_["width"] = _width;
    }

    // Verify each existing level shape against meta.json dimensions and level downscale.
    // zarr shape is [z, y, x] = [slices, height, width]
    if (!skipShapeCheck) {
        bool hasAnyPhysicalScale = false;
        for (size_t level = 0; level < zarrDs_.size(); ++level) {
            const auto& ds = zarrDs_[level];
            if (!ds) {
                continue;
            }
            hasAnyPhysicalScale = true;

            const auto& shape = ds->shape();
            const int expectedSlices = ceilDivPow2(_slices, static_cast<int>(level));
            const int expectedHeight = ceilDivPow2(_height, static_cast<int>(level));
            const int expectedWidth = ceilDivPow2(_width, static_cast<int>(level));

            // Same tolerance as the auto-generated path: canonical caches pad
            // each level independently to the next 128-boundary.
            constexpr int kMaxPerLevelPad = 128;
            auto padOK = [](long long actual, long long expected) {
                return actual >= expected && actual - expected < kMaxPerLevelPad;
            };
            if (!padOK(shape[0], expectedSlices) ||
                !padOK(shape[1], expectedHeight) ||
                !padOK(shape[2], expectedWidth)) {
                throw std::runtime_error(
                    "zarr level " + std::to_string(level) + " shape [z,y,x]=("
                    + std::to_string(shape[0]) + ", " + std::to_string(shape[1]) + ", " + std::to_string(shape[2])
                    + ") does not match expected downscaled meta.json dimensions (slices=" + std::to_string(expectedSlices)
                    + ", height=" + std::to_string(expectedHeight) + ", width=" + std::to_string(expectedWidth)
                    + ") in " + path_.string());
            }
        }

        if (!hasAnyPhysicalScale) {
            throw std::runtime_error("no physical zarr dataset directories found in " + path_.string());
        }
    }
}

std::shared_ptr<Volume> Volume::New(std::filesystem::path path)
{
    return std::make_shared<Volume>(std::move(path));
}

std::shared_ptr<Volume> Volume::NewFromUrl(
    const std::string& url,
    const std::filesystem::path& cacheRoot,
    const vc::cache::HttpAuth& authIn)
{
    namespace fs = std::filesystem;

    // Resolve s3:// URLs to https:// and detect AWS credentials
    auto resolved = vc::resolveRemoteUrl(url);
    vc::cache::HttpAuth auth = authIn;
    if (resolved.useAwsSigv4 && auth.empty()) {
        auth = vc::cache::loadAwsCredentials();
        if (auth.region.empty())
            auth.region = resolved.awsRegion;
    } else if (resolved.useAwsSigv4 && auth.region.empty()) {
        auth.region = resolved.awsRegion;
    }

    // Determine cache root
    fs::path root = cacheRoot;
    if (root.empty()) {
        root = fs::path(std::getenv("HOME") ? std::getenv("HOME") : "/tmp") / ".VC3D" / "remote_cache";
    }

    // Fetch remote metadata (downloads .zarray files, synthesizes meta.json)
    auto info = vc::cache::fetchRemoteZarrMetadata(resolved.httpsUrl, root, auth);

    // Temporarily skip shape validation (staging dir has no chunk data)
    struct SkipShapeGuard {
        bool prev;
        SkipShapeGuard() : prev(skipShapeCheck) { skipShapeCheck = true; }
        ~SkipShapeGuard() { skipShapeCheck = prev; }
    };
    SkipShapeGuard guard;

    auto vol = std::make_shared<Volume>(info.stagingDir);

    vol->isRemote_ = true;
    vol->remoteUrl_ = info.url;
    vol->remoteDelimiter_ = info.delimiter;
    vol->remoteAuth_ = auth;
    vol->remoteShardConfig_ = info.shardConfig;

    return vol;
}

int Volume::sliceWidth() const noexcept { return _width; }
int Volume::sliceHeight() const noexcept { return _height; }
int Volume::numSlices() const noexcept { return _slices; }
std::array<int, 3> Volume::shape() const noexcept { return {_width, _height, _slices}; }
double Volume::voxelSize() const
{
    return metadata_["voxelsize"].get_double();
}

vc::VcDataset *Volume::zarrDataset(int level) const {
    if (level < 0 || zarrDs_.empty())
        return nullptr;

    if (static_cast<size_t>(level) >= zarrDs_.size())
        return nullptr;

    return zarrDs_[static_cast<size_t>(level)].get();
}

size_t Volume::numScales() const noexcept {
    return zarrDs_.size();
}

std::unique_ptr<vc::cache::BlockPipeline> Volume::createTieredCache() const
{
    if (zarrDs_.empty()) return nullptr;
    std::vector<std::unique_ptr<utils::ZarrArray>> diskLevels;

    // Build level metadata from our zarr datasets
    std::vector<vc::cache::FileSystemSource::LevelMeta> levels;
    levels.reserve(zarrDs_.size());
    for (auto& ds : zarrDs_) {
        const auto& shape = ds->shape();
        const auto& chunks = ds->defaultChunkShape();
        vc::cache::FileSystemSource::LevelMeta lm;
        lm.shape = {
            static_cast<int>(shape[0]),
            static_cast<int>(shape[1]),
            static_cast<int>(shape[2])};
        lm.chunkShape = {
            static_cast<int>(chunks[0]),
            static_cast<int>(chunks[1]),
            static_cast<int>(chunks[2])};
        levels.push_back(lm);
    }

    // Get delimiter from VcDataset
    std::string delimiter = zarrDs_[0]->delimiter();

    // Create chunk source: HTTP for remote volumes, filesystem for local
    std::unique_ptr<vc::cache::VolumeSource> source;
    if (isRemote_) {
        auto httpSource = std::make_unique<vc::cache::HttpSource>(
            remoteUrl_, remoteDelimiter_, std::move(levels), remoteAuth_);
        if (remoteShardConfig_.enabled) {
            httpSource->setShardConfig(remoteShardConfig_);
        }
        source = std::move(httpSource);

        // v3 sharded disk cache: path_/0/, path_/1/, ...
        // 128³ chunks, 1024³ shards, padded to chunk boundaries.
        // Open if zarr.json exists, create if not.
        {
            int nLevels = source->numLevels();
            diskLevels.resize(nLevels);
            auto pad = [](int v, int chunk) -> size_t {
                return static_cast<size_t>((v + chunk - 1) / chunk * chunk);
            };
            for (int lvl = 0; lvl < nLevels; lvl++) {
                auto lvlPath = path_ / std::to_string(lvl);
                if (std::filesystem::exists(lvlPath / "zarr.json")) {
                    diskLevels[lvl] = std::make_unique<utils::ZarrArray>(
                        utils::ZarrArray::open(lvlPath));
                } else {
                    auto shape = source->levelShape(lvl);
                    utils::ZarrMetadata meta;
                    meta.version = utils::ZarrVersion::v3;
                    meta.node_type = "array";
                    meta.shape = {pad(shape[0], 128), pad(shape[1], 128), pad(shape[2], 128)};
                    meta.chunks = {1024, 1024, 1024};
                    meta.dtype = utils::ZarrDtype::uint8;
                    meta.fill_value = 0;
                    meta.chunk_key_encoding = "default";
                    utils::ShardConfig sc;
                    sc.sub_chunks = {128, 128, 128};
                    meta.shard_config = std::move(sc);
                    diskLevels[lvl] = std::make_unique<utils::ZarrArray>(
                        utils::ZarrArray::create(lvlPath, std::move(meta)));
                }
            }
            fprintf(stderr, "[Volume] Cold cache: %d levels at %s\n",
                    nLevels, path_.c_str());
        }
    } else {
        source = std::make_unique<vc::cache::FileSystemSource>(
            path_, delimiter, std::move(levels));

        // Network mount disk caching disabled — needs per-level conversion
        if (mountInfo_.type == vc::FilesystemType::NetworkMount) {
            fprintf(stderr, "[Volume] Network mount detected — disk cache not yet per-level, skipping\n");
        }
    }

    // Build dataset pointers for the decompressor
    std::vector<vc::VcDataset*> dsPtrs;
    dsPtrs.reserve(zarrDs_.size());
    for (auto& ds : zarrDs_) {
        dsPtrs.push_back(ds.get());
    }
    auto decompress = vc::cache::makeVcDecompressor(dsPtrs);

    vc::cache::BlockPipeline::Config config;
    config.volumeId = id();
    config.bytes = cacheBudgetHot_;
    config.encodeParams = encodeParams_;

    // Canonical-passthrough detection. Remote sources whose shard layout
    // matches our local cache (zarr v3, sharded, 128^3 inner H.265 chunks,
    // 1024^3 shards) get whole-shard byte-passthrough — one HTTP request +
    // one disk write per source shard instead of decoding and re-encoding
    // 512 inner chunks. We probe level 0 zarr.json directly because the
    // remoteShardConfig from NewFromUrl isn't always populated.
    if (isRemote_) {
        try {
            auto resolved = vc::resolveRemoteUrl(remoteUrl_);
            const std::string base = resolved.httpsUrl
                + (resolved.httpsUrl.back() == '/' ? "" : "/");
            auto json = vc::cache::httpGetString(base + "0/zarr.json", remoteAuth_);
            if (!json.empty()) {
                auto meta = utils::detail::parse_zarr_json(json);
                if (utils::is_canonical_vc3d(meta)
                    && meta.chunks.size() >= 3
                    && meta.chunks[0] == 1024
                    && meta.chunks[1] == 1024
                    && meta.chunks[2] == 1024) {
                    config.canonicalSourceShard = {1024, 1024, 1024};
                    fprintf(stderr,
                        "[Volume] canonical-passthrough enabled (source "
                        "shards 1024x1024x1024 match local)\n");
                }
            }
        } catch (const std::exception& e) {
            fprintf(stderr,
                "[Volume] canonical-passthrough detection failed: %s\n",
                e.what());
        }
    }
    if (isRemote_ || mountInfo_.type == vc::FilesystemType::NetworkMount) {
        if (ioThreads_ > 0) {
            config.ioThreads = ioThreads_;
        } else if (mountInfo_.parallelCount > 0) {
            config.ioThreads = mountInfo_.parallelCount;
        } else {
            config.ioThreads = 8;  // HTTP/2 multiplexing: fewer connections, many streams each
        }
        fprintf(stderr, "[Volume] IO threads: %d\n", config.ioThreads);
    }

    return std::make_unique<vc::cache::BlockPipeline>(
        std::move(config),
        std::move(source),
        std::move(decompress),
        std::move(diskLevels));
}

// ============================================================================
// Cache management
// ============================================================================

void Volume::ensureTieredCache() const
{
    std::call_once(cacheOnce_, [this]() {
        auto* self = const_cast<Volume*>(this);
        tieredCache_ = self->createTieredCache();
    });
}

vc::cache::BlockPipeline* Volume::tieredCache()
{
    ensureTieredCache();
    return tieredCache_.get();
}

void Volume::setCacheBudget(size_t hotBytes)
{
    cacheBudgetHot_ = hotBytes;
}

void Volume::setIOThreads(int count)
{
    ioThreads_ = count;
}

void Volume::setEncodeParams(const utils::VideoCodecParams& params)
{
    if (tieredCache_) {
        fprintf(stderr, "[Volume] WARNING: setEncodeParams() called after cache "
                        "already created — ignoring\n");
        return;
    }
    encodeParams_ = params;
}

// ============================================================================
// Sampling API
// ============================================================================

// Helper: apply optional post-processing from SampleParams in-place.
static void applyOptionalPostProcess(cv::Mat_<uint8_t>& img,
                                     const vc::SampleParams& params)
{
    if (!params.postProcess) return;
    vc::applyPostProcess(img, *params.postProcess);
}

// Helper: scale level-0 coords to pyramid level coords.
static const cv::Mat_<cv::Vec3f>& scaleCoords(const cv::Mat_<cv::Vec3f>& coords, int level)
{
    if (level <= 0) return coords;
    // Thread-local buffer avoids per-tile allocation for the scaled copy
    thread_local cv::Mat_<cv::Vec3f> scaled;
    float scale = 1.0f / static_cast<float>(1 << level);
    if (scaled.rows != coords.rows || scaled.cols != coords.cols) {
        scaled.create(coords.size());
    }
    const int total = coords.rows * coords.cols;
    const auto* src = coords.ptr<cv::Vec3f>();
    auto* dst = scaled.ptr<cv::Vec3f>();
    for (int i = 0; i < total; ++i) {
        dst[i] = src[i] * scale;
    }
    return scaled;
}

void Volume::sample(cv::Mat_<uint8_t>& out,
                    const cv::Mat_<cv::Vec3f>& coords,
                    const vc::SampleParams& params)
{
    const auto& scaled = scaleCoords(coords, params.level);
    readInterpolated3D(out, tieredCache(), params.level, scaled, params.method);
    applyOptionalPostProcess(out, params);
}

void Volume::sample(cv::Mat_<uint16_t>& out,
                    const cv::Mat_<cv::Vec3f>& coords,
                    const vc::SampleParams& params)
{
    const auto& scaled = scaleCoords(coords, params.level);
    readInterpolated3D(out, tieredCache(), params.level, scaled, params.method);
}

int Volume::sampleBestEffort(cv::Mat_<uint8_t>& out,
                              const cv::Mat_<cv::Vec3f>& coords,
                              const vc::SampleParams& params)
{
    const int nScales = static_cast<int>(numScales());
    const int level = std::clamp(params.level, 0, std::max(0, nScales - 1));
    const auto& scaled = scaleCoords(coords, level);
    readInterpolated3D(out, tieredCache(), level, scaled, params.method);
    if (!out.empty())
        applyOptionalPostProcess(out, params);
    return level;
}

void Volume::sampleComposite(cv::Mat_<uint8_t>& out,
                              const cv::Mat_<cv::Vec3f>& coords,
                              const cv::Mat_<cv::Vec3f>& normals,
                              const vc::SampleParams& params)
{
    float scale = (params.level > 0) ? (1.0f / static_cast<float>(1 << params.level)) : 1.0f;
    const auto& scaled = scaleCoords(coords, params.level);
    readCompositeFast(out, tieredCache(), params.level, scaled, normals, scale,
                      params.zStart, params.zEnd,
                      params.composite.value_or(CompositeParams{}),
                      params.method);
    applyOptionalPostProcess(out, params);
}

int Volume::sampleCompositeBestEffort(cv::Mat_<uint8_t>& out,
                                       const cv::Mat_<cv::Vec3f>& coords,
                                       const cv::Mat_<cv::Vec3f>& normals,
                                       const vc::SampleParams& params)
{
    const int nScales = static_cast<int>(numScales());
    const int level = std::clamp(params.level, 0, std::max(0, nScales - 1));
    vc::SampleParams lvlParams = params;
    lvlParams.level = level;
    sampleComposite(out, coords, normals, lvlParams);
    return level;
}


int Volume::samplePlaneBestEffort(cv::Mat_<uint8_t>& out,
                                   const cv::Vec3f& origin,
                                   const cv::Vec3f& vx_step,
                                   const cv::Vec3f& vy_step,
                                   int width, int height,
                                   const vc::SampleParams& params)
{
    const int nScales = static_cast<int>(numScales());
    const int level = params.level;

    int lvl = std::clamp(level, 0, std::max(0, nScales - 1));
    float scale = (lvl > 0) ? (1.0f / static_cast<float>(1 << lvl)) : 1.0f;
    samplePlane(out, tieredCache(), lvl,
                origin * scale, vx_step * scale, vy_step * scale,
                width, height, params.method);
    if (!out.empty())
        applyOptionalPostProcess(out, params);
    return lvl;
}

int Volume::samplePlaneCompositeBestEffortARGB32(
    uint32_t* outBuf, int outStride,
    const cv::Vec3f& origin, const cv::Vec3f& vx_step, const cv::Vec3f& vy_step,
    const cv::Vec3f& normal, float zStep, int zStart, int numLayers,
    int width, int height,
    const std::string& compositeMethod,
    const uint32_t lut[256])
{
    samplePlaneCompositeARGB32(outBuf, outStride, tieredCache(), 0,
        origin, vx_step, vy_step,
        normal, zStep, zStart, numLayers,
        width, height, compositeMethod, lut);
    return 0;
}

// ============================================================================
// Composite-aware chunk helpers
// ============================================================================


// ============================================================================
// Data bounds
// ============================================================================

void Volume::computeDataBounds()
{
    // Set bounds to the full volume shape — no scanning needed.
    dataBounds_.minX = 0;
    dataBounds_.maxX = _width - 1;
    dataBounds_.minY = 0;
    dataBounds_.maxY = _height - 1;
    dataBounds_.minZ = 0;
    dataBounds_.maxZ = _slices - 1;
    dataBounds_.valid = true;

    // Push to cache so ChunkSampler can skip chunks outside bounds
    ensureTieredCache();
    if (tieredCache_) {
        tieredCache_->setDataBounds(
            dataBounds_.minX, dataBounds_.maxX,
            dataBounds_.minY, dataBounds_.maxY,
            dataBounds_.minZ, dataBounds_.maxZ);
    }

    fprintf(stderr, "[Volume] dataBounds: x=[%d, %d] y=[%d, %d] z=[%d, %d] (full volume shape)\n",
            dataBounds_.minX, dataBounds_.maxX,
            dataBounds_.minY, dataBounds_.maxY,
            dataBounds_.minZ, dataBounds_.maxZ);
}

const Volume::DataBounds& Volume::dataBounds() const
{
    std::call_once(boundsOnce_, [this] {
        const_cast<Volume*>(this)->computeDataBounds();
    });
    return dataBounds_;
}


