tr_config:
  patch_size: [128,128,128]

dataset_config:
    data_format: zarr         # or "image", "napari"
    data_path: /mnt/raid_nvme/datasets/tests
    image_dirname: images     # for adapter="image"
    label_dirname: labels     # optional if you’re loading labels

    meshes:
      enabled: true
      dirname: meshes         # resolved under data_path
      manifest: meshes/manifest.yaml

    targets:
      8um:
        out_channels: 1