tr_config:
  patch_size: [128, 128, 128]
  batch_size: 1
  enable_deep_supervision: false

model_config:
  pretrained_backbone: "/home/giorgio/Projects/dino-vesuvius/dino-checkpoints/checkpoint_step_342500.pt"
  pretrained_decoder_type: "pixelshuffle_conv"
  freeze_encoder: true
  input_shape: [128, 128, 128]

dataset_config:
  min_labeled_ratio: 0
  min_bbox_percent: 0
  normalization_scheme: "zscore"
  skip_patch_validation: true
  targets:
    surface:
      out_channels: 2
      activation: "none"
      losses:
        - name: "MedialSurfaceRecall"
          weight: 1.0
