name: Test vesuvius Python

on:
  pull_request:
    paths:
      - 'vesuvius/**'
      - '.github/workflows/test-vesuvius.yml'

jobs:
  test-vesuvius-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install vesuvius package locally
      working-directory: vesuvius
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Test vesuvius import
      run: |
        python -c "import vesuvius"
    - name: Test vesuvius trainer
      run: |
        vesuvius.train -h
    - name: Test vesuvius.predict
      run: |
        vesuvius.predict -h
    - name: Test vesuvius.blend_logits
      run: | 
        vesuvius.blend_logits -h
    - name: Test vesuvius.finalize_outputs
      run: | 
        vesuvius.finalize_outputs -h
    
