name: Continuous Integration (CI)

on:
  pull_request:
    paths:
      - 'volume-cartographer/**'
      - '.github/workflows/vc3d-ci.yml'

permissions:
  contents: read

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./volume-cartographer
          file: ./volume-cartographer/ubuntu-24.04-noble.Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ github.repository_owner }}/volume-cartographer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # load: true  # uncomment if you want the image loaded into the runner for tests
