name: Publish Vesuvius to PyPI

on:
  push:
    tags:
      - 'vesuvius-v*'

permissions:
  contents: read
  id-token: write  # Required for OIDC authentication with PyPI

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vesuvius  # Adjust according to your repo structure
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build the package
        run: |
          python -m build --sdist --wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
