name: Publish Vesuvius to PyPI

on:
  push:
    tags:
      - 'vesuvius-v*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vesuvius
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build the package
        run: |
          python -m build --sdist --wheel

      - name: Get version from setup.py
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Determine Repository URL
        id: repository
        run: |
          if [[ "${{ steps.get_version.outputs.version }}" == *"rc"* ]]; then
            echo "repository_url=https://test.pypi.org/legacy/" >> $GITHUB_OUTPUT
          else
            echo "repository_url=https://upload.pypi.org/legacy/" >> $GITHUB_OUTPUT
          fi

      - name: Publish to PyPI/TestPyPI using Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ steps.repository.outputs.repository_url }}
          auth-provider: pypi
